stackrox/scanner

e2etests/testcase_test.go
pkg/vulnloader/nvdloader/manual.go

Information based on https://tanzu.vmware.com/security/cve-2022-22963 and https://sysdig.com/blog/cve-2022-22963-spring-cloud/

Add CVE-2022-22963

---

.circleci/config.yml
Makefile
scripts/ci/lib.sh
scripts/lib.sh

Now that StackRox is open source 🎉, there are a number of other repos and processes that depend on images being found under quay.io/stackrox-io. This PR pushes scanner images there also.

Push images to the public registry

---

.github/dependabot.yml

Update Dependabot reviewers

---

e2etests/testcase_test.go

Simply don't test with this image at this time. Finding a replacement image to test the same concept may be challenging, so I created a [Jira ticket for it.](https://issues.redhat.com/browse/ROX-10926).

Remove non-existent image for now

---

.github/dependabot.yml

Monitor docker images with dependabot.

Add dependabot for docker images

---

image/scanner/rhel/Dockerfile

chown nobody:nobody genesis_manifests.json

---

scripts/ci/lib.sh

fix CI scripts

---

Makefile
scripts/ci/jobs/db-integration-tests.sh

Adapted from https://github.com/stackrox/stackrox/pull/2420 and tested with https://github.com/openshift/release/pull/30583

ROX-11402: Migrate DB integration tests to OSCI

---

scripts/ci/lib.sh

OSCI fix Slack again

---

.openshift-ci/build/Dockerfile.generate-db-dump
.openshift-ci/build/generate-db-dump.sh
.openshift-ci/build/generate-genesis-dump.sh
scripts/ci/gate-jobs-config.json
scripts/ci/jobs/db-integration-tests.sh
scripts/ci/jobs/diff-dumps.sh
scripts/ci/jobs/e2etests/e2e-tests.sh
scripts/ci/jobs/e2etests/slim-e2e-tests.sh
scripts/ci/jobs/store-db-dump.sh
scripts/ci/jobs/store-genesis-dump.sh
scripts/ci/jobs/unit-tests.sh
scripts/ci/jobs/upload-db-dump.sh
scripts/ci/lib.sh
scripts/ci/postgres.sh

Tested by https://github.com/openshift/release/pull/30616

ROX-11842: Migrate DB dump to OSCI

---

Makefile
chart/values.yaml
scripts/ci/lib.sh

Based on https://github.com/stackrox/scanner/pull/815

remove gcr image

---

scripts/ci/jobs/push-images.sh

Update hub-comment call

---

e2etests/testcase_test.go

a few vulns were coincidentally updated today, so updating the tests to reflect this

update e2e tests based on latest vuln updates

---

Makefile
tools/test/go.mod
tools/test/go.sum
tools/test/tools-import.go

Based on https://github.com/stackrox/stackrox/pull/2586

Update go-junit-report to v2.0.0

---

tools/clean_autogen_protos.py

See corresponding PR in stackrox/stackrox#2649

Update clean_autogen_protos.py script

---

api/v1/common/dep_map.go
api/v1/common/dep_map_test.go
api/v1/models.go
database/string_map.go
ext/featurens/busybox/busybox.go
pkg/component/type.go

My local machine is running go1.19, and it triggers these style updates. I imagine as other people start using go1.19, they will run into this, too, so we might as well update these things now.

go1.19 style updates

---

go.mod

Based on https://github.com/stackrox/stackrox/pull/2784

update gomod to 1.17

---

Makefile
chart/templates/db-deployment.yaml
chart/templates/deployment.yaml
chart/values.yaml

Update the image name to reflect the name of the built images. Also, ensure the local image is used when using `make deploy-local`

Fix local deployment

---

image/db/rhel/scripts/docker-entrypoint.sh

https://github.com/docker-library/postgres/pull/964

Update docker-entrypoint.sh to match latest version

---

.editorconfig

Based on https://github.com/stackrox/stackrox/pull/3192

update .editorconfig for protobufs

---

e2etests/testcase_test.go

See https://access.redhat.com/errata/RHSA-2022:7745

e2e: update fixedBy version for freetype in RHEL 8

---

e2etests/testcase_test.go

See https://access.redhat.com/errata/RHSA-2022:7865

e2e: update jenkins-2-plugins fixedby version

---

scripts/ci/lib.sh

remove user from slack notification

---

e2etests/node_scan_rhcos_test.go

This PR aims at refactoring the e2e tests for node scanning, so that the assertions (equals vs. is subset) are clearer to read.
This is a follow-up to the discussion in https://github.com/stackrox/scanner/pull/1045#issuecomment-1377950931

Refactor e2e RHCOS tests

---

.openshift-ci/Dockerfile.build_root
.openshift-ci/build/Dockerfile.build-bundle
.openshift-ci/build/Dockerfile.build-db-bundle
.openshift-ci/build/Dockerfile.generate-db-dump
.openshift-ci/build/Dockerfile.generate-genesis-dump
BUILD_IMAGE_VERSION
README.md

Will update the `go.mod` files to 1.19 in a separate PR

Update to go1.19.4

---

scripts/ci/lib.sh

The checks were introduced in Git 2.28.0. This message appears when a repository's ownership is unclear and Git attempts to warn the user about this issue. After the latest build image upgrade to bump to go-1.9, CI started failing due to this check.
This change is a mirrored change of the [steps taken in stackrox/stackrox](https://github.com/stackrox/stackrox/commit/48fe67a44e1e064898e288bd0d82d9204bea701d).
Build targets in Makefile might also need an update. This will be addressed in a separate PR after some testing.

Disable safe directory checks in git on CI

---

database/pgsql/feature.go
database/pgsql/namespace.go
database/pgsql/pgsql.go
go.mod
go.sum

LRU cache is disabled since #168 
Maybe it's time to remove it completly.

Remove lru cache

---

e2etests/testcase_test.go

https://access.redhat.com/errata/RHSA-2023:0697

e2e: update jenkins-2-plugins FixedBy

---

e2etests/node_scan_rhcos_test.go

Noticed this in when testing a separate PR

e2e: RHSA-2022:7089 updated CVSSv3 score

---

e2etests/testcase_test.go

Update FixedBy for UBI9 OpenSSL / VIM 

---

pkg/cpeutils/utils.go
pkg/cpeutils/utils_test.go

Discovered this was possible when viewing the output of "generate-genesis-dumps" in CI

account for OpenShift 4.x on RHEL 7

---

e2etests/testcase_test.go

https://access.redhat.com/errata/RHSA-2023:2523

Fixed fixedby version for RHSA-2023:2523

---

api/v1/orchestratorscan/service.go

Return error instead of nil when version conversion fails

return err when version conversion fails

---

go.mod
go.sum

See https://github.com/stackrox/stackrox/pull/6941

chore(deps): bump docker-registry-client

---

go.mod
go.sum

not quite sure what happened here, but this should clean it up

chore: reformat go.mod

---

image/db/rhel/Dockerfile
image/db/rhel/Dockerfile.slim
image/scanner/rhel/Dockerfile
image/scanner/rhel/Dockerfile.slim

See https://github.com/stackrox/stackrox/pull/6795

build: use ubi8 latest

---

pkg/env/integersetting.go

This is so https://github.com/stackrox/scanner/pull/1287 can progress

chore: allow integer env vars

---

pkg/vulnloader/nvdloader/loader.go

This PR bumps the number of retries from 3 to 5, and it also retries upon JSON decode error.

chore(nvd): add more retries

---

e2etests/testcase_test.go

See the following:
* https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2021-24112
* https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2021-26701
* https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2021-31204
* https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2020-1045
* https://services.nvd.nist.gov/rest/json/cves/2.0?cveId=CVE-2020-1597

chore(e2e): fix .NET Core Runtime tests

---

.github/CODEOWNERS

Copied content from `stackrox` https://github.com/stackrox/stackrox/blob/master/.github/CODEOWNERS and hope it would just work.

(chore): Setup `CODEOWNERS` for `.tekton` directory

---

e2etests/testcase_test.go

See [RHSA-2024:0808](https://access.redhat.com/errata/RHSA-2024:0808) for details

fix(e2e): update test

---

scripts/ci/jobs/diff-dumps.sh

Update v4 file download URL

---

image/db/rhel/konflux.Dockerfile
image/scanner/rhel/konflux.Dockerfile

Similar to https://github.com/stackrox/collector/pull/1633

chore: Expand RHACS in Konflux Dockerfile labels

---

e2etests/layer_test.go

This ensures it will not be deleted

chore(ci): move docker image to quay

---

api/grpc/logging_interceptor.go
pkg/clairify/server/middleware/log.go

chore: stop logging pings

---

.github/workflows/ci.yaml
.github/workflows/sanity-check-vuln-updates.yaml
.openshift-ci/Dockerfile.build_root
.openshift-ci/build/Dockerfile.build-bundle
.openshift-ci/build/Dockerfile.build-db-bundle
.openshift-ci/build/Dockerfile.generate-db-dump
.openshift-ci/build/Dockerfile.generate-genesis-dump
BUILD_IMAGE_VERSION

Update the CI image. See https://github.com/stackrox/rox-ci-image/pull/212 for more details.

chore(ci): use UBI 8 based rox-ci-image

---

e2etests/testcase_test.go

See https://access.redhat.com/errata/RHSA-2024:6162 for more information

e2e: account for RHSA-2024:6162

---

.tekton/scanner-component-pipeline.yaml

chore: Update konflux pipelines

---

e2etests/testcase_test.go
ext/vulnsrc/manual/manual.go

Followup to https://github.com/stackrox/scanner/pull/1668

chore: update cups vulns yet again

---

image/scanner/dump/genesis_manifests.json

Generate new genesis dump for 2.35.0

---

.tekton/scanner-build.yaml
.tekton/scanner-db-build.yaml
.tekton/scanner-db-slim-build.yaml
.tekton/scanner-slim-build.yaml

Same as https://github.com/stackrox/stackrox/pull/13147 but for scanner repo.

ROX-26765: Rename pipelineruns to enable on-push rerunning

---

.tekton/scanner-build.yaml
.tekton/scanner-component-pipeline.yaml
.tekton/scanner-db-build.yaml
.tekton/scanner-db-slim-build.yaml
.tekton/scanner-slim-build.yaml

Similar to https://github.com/stackrox/stackrox/pull/13194 plus PR branch change from https://github.com/stackrox/stackrox/pull/13076

build: Update Konflux pipelines

---

.github/renovate.json5

Took the recent one from StackRox.
See https://github.com/stackrox/stackrox/pull/13485

chore: Update Renovate config

---

.tekton/scanner-build.yaml
.tekton/scanner-db-build.yaml
.tekton/scanner-db-slim-build.yaml
.tekton/scanner-slim-build.yaml

Context:
* https://issues.redhat.com/browse/ROX-24530
* https://github.com/stackrox/stackrox/pull/13757

ROX-24530: let Konflux images expire after 13w

---

.github/actions/cache-go-dependencies/action.yaml

Hoping this fixes all my problems

chore(ci): bump actions/cache to v4

---

.tekton/scanner-component-pipeline.yaml

See https://github.com/stackrox/konflux-tasks/pull/37

ROX-27831: set image expiration based on event type and target branch

---

.github/dependabot.yml

Based on https://github.com/stackrox/stackrox/pull/14263

chore(dependabot): update custom actions too

---

scripts/ci/deploy.sh

Backporting https://github.com/stackrox/scanner/pull/1835

bump ready timeout for e2e tests (#1835)

---

e2etests/testcase_test.go
e2etests/utils.go

Account for a new vuln + increase gRPC size

fix(e2e): fix test + gRPC message size

---

.tekton/scanner-component-pipeline.yaml

The new task from https://github.com/stackrox/konflux-tasks/pull/41 is used.
See https://github.com/stackrox/konflux-tasks/pull/41#issuecomment-2757538219
Also, EC does not seem to be complaining about these new tasks which is nice.

ROX-27856: Add BigQuery metrics to Konflux pipelines

---

.tekton/scanner-component-pipeline.yaml

Includes all the changes as of https://github.com/stackrox/konflux-tasks/pull/45 merge.
Verified by looking at bigtable data.

ROX-27856: Use modified version of the metrics task

---

pkg/rhelv2/fetcher.go
pkg/rhelv2/rhelv2.go

(cherry picked from commit 7b15e0e99d7d343213ac4f36ffd0fcb920a32f97)

fix(ci): increase timeout processing RH OVAL data (#1820)

---

rpms.in.yaml

The same change as discussed in https://github.com/stackrox/stackrox/pull/15114#discussion_r2073414884

ROX-27638: Add docs link to `rpms.in.yaml`

---

rpms.in.yaml
rpms.lock.yaml

This follows up on the promise of testing I made in https://github.com/stackrox/scanner/pull/1875
Will check that Konflux CI feels happy.
This needs to be merged before we can see if it has an effect on MintMaker.

ROX-29108: Induce RPM lockfile renovation

---

.tekton/scanner-build.yaml
.tekton/scanner-db-build.yaml
.tekton/scanner-db-slim-build.yaml
.tekton/scanner-slim-build.yaml

Per ticket.
Validation - only CI.

ROX-29479: Change Scanner V2 repos for Konflux builds

---

.tekton/determine-image-tag-task.yaml
.tekton/fetch-scanner-data-task.yaml
.tekton/scanner-build.yaml
.tekton/scanner-component-pipeline.yaml
.tekton/scanner-db-build.yaml
.tekton/scanner-db-slim-build.yaml
.tekton/scanner-slim-build.yaml
scripts/konflux/fetch-scanner-data.sh

PR for the first batch of commits
Obtained via
```bash
$ git cherry-pick 9807c27 6e75b71 4636bb8 ef9c285 297b8d0 97c41a7 ff7e0f3 bcae68c e589d29
```

ROX-27060: Konflux Patches for 4.6: Batch 1

---

.github/CODEOWNERS
.github/renovate.json5
.syft.yaml
.tekton/scanner-build.yaml
.tekton/scanner-component-pipeline.yaml
.tekton/scanner-db-build.yaml
.tekton/scanner-db-slim-build.yaml
.tekton/scanner-slim-build.yaml
image/db/rhel/konflux.Dockerfile
image/scanner/rhel/konflux.Dockerfile
rpms.in.yaml
rpms.lock.yaml
rpms.rhel.repo

Obtained via
```sh
$ git cherry-pick a1f7c2333777bfa41b9495af997bb65cd97f8a90 6677b83b8d7d018195e4e2fb148c1751dddf86a0
```

ROX-28955: Konflux Patches for 4.7

---

.github/CODEOWNERS
.github/renovate.json5
.github/workflows/auto-approve.yml
.tekton/scanner-build.yaml
.tekton/scanner-db-build.yaml
.tekton/scanner-db-slim-build.yaml
.tekton/scanner-slim-build.yaml

backport(release-2.37): renovate auto merge

---

image/db/rhel/scripts/download.sh

Backport https://github.com/stackrox/scanner/pull/2092

backport(release-2.37) fix(ci): add specific psql version to fix s390x

---

.tekton/scanner-component-pipeline.yaml

See the related ticket.
See my comments below.

ROX-30898: Assign index image tag differently

---

.github/renovate.json5

According to MintMaker announcement.

ROX-30899: Rename `rpm` -> `rpm-lockfile` manager

---

.github/renovate.json5
.tekton/scanner-component-pipeline.yaml

Cherry-picks of
1. https://github.com/stackrox/scanner/pull/2195
2. https://github.com/stackrox/scanner/pull/2201
Only CI.

ROX-30898, ROX-30899: Konflux backports / 4.8
