stackrox/scanner

image/scanner/scripts/import-additional-cas
Update the system trusted CA bundle with the ones injected by the Openshift Network Operator and mounted as a kubernetes secret volume.
The script is copied from the stackrox repo and enriched with some comments and the `extract` parameter for verbosity. Once merged, the script will be copied back to stackrox for consistency.
This PR is a resurrection of #604.
Tests performed previously when merging to the stackrox repository.
=> ROX-9497: Copy custom trusted CA bundles injected by OpenShift Network Operator

database/namespace_mapping.go
Debian 11 is "stable". See https://www.debian.org/releases/, https://www.debian.org/releases/testing/releasenotes, and https://deb.debian.org/debian/dists/
=> Update Debian name mappings

image/db/rhel/Dockerfile, image/db/rhel/scripts/docker-entrypoint.sh
Create an empty `/docker-entrypoint-initdb.d` in the scanner-db-slim container.
Scanner-db-slim will fail otherwise. In the PSQL community entry point script we "re-use", there is a check for the existence of that directory. We create the directory empty in the container, rather than modifying the script -- the more pristine the script is, the easier it will be for us to pull from upstream in the future.
Deployed to Openshift manually.
=> Create `/docker-entrypoint-initdb.d` in the scanner-db-slim container

pkg/updater/slim_updater.go
Remove usage of `path` when interacting with the file system, replace it the `filepath`.
It allows unit tests to run in any development environment since they can create temporary directories. Also, it keeps the codebase ready for additional testing and running containerized environments in the future, if any.
Relying on CI.
=> fix: Remove `path` and use `filepath`

pkg/elf/elf.go, pkg/elf/elf_test.go
This is the other part why we did not find the reader issue earlier.
=> Elf check shall not hide io error

pkg/elf/elf.go, pkg/tarutil/tarutil.go
Noticed this when I was scanning an image with whiteout files. I kept seeing logs like these:
```
ERRO[0026] Failed to get dependencies for usr/lib/ssl/misc/.wh.CA.sh: EOF 
ERRO[0026] Failed to get dependencies for usr/lib/ssl/misc/.wh.c_hash: EOF 
ERRO[0026] Failed to get dependencies for usr/lib/ssl/misc/.wh.c_info: EOF 
```
as well as for other empty files:
```
ERRO[0026] Failed to get dependencies for usr/bin/perlthanks: EOF 
ERRO[0026] Failed to get dependencies for usr/bin/pstruct: EOF 
ERRO[0026] Failed to get dependencies for usr/bin/s2p: EOF 
```
=> Do not attempt to retrieve ELF metadata for small files

pkg/vulnloader/nvdloader/manual.go
Add a manual entry for CVE-2017-5638 that specifies `VersionEndExcluding` instead of individual cpe matches.
Without the `VersionEndExcluding` Scanner cannot determine which struts version fixes this vuln, which in turn will be shown in the UI as "not fixable":
ROX-11037
Added `generate-dump-on-pr` label to this PR, forcing the generation of the vulnerability definitions bundle. Then, pulled the previous CVE-2017-5638 and diffed it with the new generated one:
```
% gsutil -m cp -r gs://roxci-artifacts/scanner/422053bd-4481-424c-8550-76b17d7c6248/276767-generate-genesis-dump/genesis-dump.zip .
% unzip genesis-dump.zip -d genesis-dump/
...
% cat genesis-dump/nvd/2017.json | jq '.CVE_Items[] | select(.cve.CVE_data_meta.ID == "CVE-2017-5638")' > /tmp/old.CVE-2017-5638.json
% cat …
```
=> ROX-11037: Add manual entry for CVE-2017-5638

.circleci/config.yml
There is no need to run the DB integration tests using a live Scanner DB, so might as well move the tests elsewhere so they do not depend on a pre-existing deployment.
Also use the postgres:12-bullseye image instead of postgres:12.0-alpine for two reasons:
1. Let's us use the latest version of PostgreSQL 12
2. We took the docker-entrypoint.sh from the [Debian version](https://github.com/docker-library/postgres/blob/master/12/bullseye/docker-entrypoint.sh), so this gives us a sense of consistency (kind of)
=> Separate DB integration tests to a separate job

.github/dependabot.yml, .gitignore, Makefile, tools/test/go.mod, tools/test/go.sum, tools/test/tools-import.go
This is copied from https://github.com/stackrox/stackrox/blob/master/make/stackrox.mk.
This is meant to be used in OpenShift CI to get clearer test results. Once this is merged, I can update https://github.com/stackrox/scanner/pull/784 to add JUnit output to the E2E tests and I can add JUnit output to the already-migrated unit-tests.
=> Add JUnit output to E2E test results

.circleci/collect-service-logs.sh, .circleci/config.yml, chart/templates/db-deployment.yaml, chart/templates/deployment.yaml, image/db/rhel/Dockerfile, image/db/rhel/scripts/docker-entrypoint.sh
This PR makes a few PostgreSQL-related updates:
* Move Scanner DB's secret out of the main Scanner DB container
* This moves the secret into the init container, as it is only needed there
* Some Dockerfile cleanup
We also start looking at initContainer logs
=> ROX-11335: Move Scanner DB secret out of main Scanner DB container

pkg/features/list.go, pkg/rhelv2/rpm/rpm.go, pkg/rhelv2/rpm/rpm_language_analyzer.go, pkg/rhelv2/rpm/rpm_test.go, pkg/rpm/database.go, pkg/rpm/database_test.go, tools/large-git-files/allowlist
Add support for scanning images using `rpm` on top of SQLite database backend, which is the default RPM database backend for `>= 4.16`. The support is behind a feature flag that defaults to `false`.
RHEL images from release 9 onward are built on `rpm >= 4.16`. Supporting the SQLite database backend is a requirement to support these images in Stackrox Scanner. We will need to adopt UBI9 to enable RHEL9 support because Stackrox Scanner relies on the `rpm` binary in the container image to query the RPM database. 
ROX-10929
Due to an issue with CircleCI docker runtime that prevents UBI9 containers to execute, we cannot bump the Scanner image to it. The issue is that UBI9 requires a specific seccomp profile setup that is not currently available in CircleCI and cannot be modified when building …
=> ROX-10929: Add support for RHEL9 images

chart/templates/db-deployment.yaml, chart/templates/deployment.yaml, image/db/rhel/Dockerfile, image/scanner/rhel/Dockerfile
Let the kubelet validate the image does not run as UID 0 (root). Putting this in the pod's security context means it applies to all containers in the pod (anything in a specific container's security context will take precedence).
By adding this, we cannot use named user/group for the `USER` field in the Dockerfiles, so this also reverts `USER postgres:postgres` back to `USER 70:70`
Also move the `runAsGroup` and `runAsUser` to the pod-level, as the two containers have the same security context, otherwise.
=> Add runAsNonRoot to pod's security context

pkg/vulnloader/k8sloader/loader.go, pkg/vulnloader/nvdloader/enricher.go
OSCI does not forward `SSH_AUTH_SOCK`, so I don't think we can use ssh creds anymore for this. Good news: these repos are open sourced, so we don't really need creds! So, let's switch to HTTPS auth instead
=> use https instead of ssh for git

ext/vulnsrc/stackrox/stackrox.go
This is now publicly available, so no need to have special permissions to access it.
=> Remove need for service account for StackRox GCP vuln source

ext/vulnsrc/stackrox/stackrox.go, pkg/wellknownnamespaces/set.go
Debian 9 has reached EOL, which means Debian maintainers deleted all traces of it from the security tracker. Since we are not deprecating support yet, we stored the latest Debian 9 vulns in a GCP bucket like we did for Debian 8.
This PR adds support for reading from the Debian 9 vulns bucket and also adds the proper scan note
=> Support stale Debian 9 vulns

.circleci/config.yml, scripts/ci/lib.sh
This registry is no longer used, so let's stop pushing to it.
=> stop pushing to stackrox.io

.circleci/config.yml
CCI unit-tests and style-checks are no longer required, either. Instead, the prow versions are.
Not deleting yet because the hourly versions have yet to migrate
=> Remove CCI unit-tests, style-checks, and db-integration-tests from build steps

scripts/ci/jobs/push-images.sh
Blindly copying from the stackrox repo means we get the same comment, which doesn't make sense for Scanner. Updating it here
=> update hub comment

Makefile
Introducing the `| tee whatever` meant the exit code would be `0` because the `tee` succeeded. Add `set -o pipefail` to ensure the exist code is returned properly
=> add pipefail to tests

scripts/ci/gke.sh
Ensure we teardown the correct zone, which was set in the `create_cluster` step
=> Set GKE zone upon teardown

scripts/ci/lib.sh
E2E tests use the open-source images in quay.io/stackrox-io instead of quay.io/rhacs-eng, so let's poll for those images instead
=> Poll stackrox-io instead of rhacs-eng for E2E test images

ext/featurefmt/driver.go, pkg/elf/elf.go, pkg/tarutil/tarutil.go
gitlab EE image returned 6500 paths
Now it returns 1300 paths including .so's
TBD if we can remove .so from the path
=> Check for ELF executables and scripts that start with shebang

pkg/wellknownnamespaces/set.go
Ubuntu 21.10 reached EOL July 14, 2022, so let's ensure users know this OS is stale
=> ROX-11779: Deprecate Ubuntu 21.10

.openshift-ci/build/build-bundle.sh
Without this, we inject `blahblah-dirty` into the Scanner binary, which means Scanner will print "Running Scanner version: blahblah-dirty", which will confuse non-devs
=> Ensure Scanner binary isn't "dirty"

make/protogen.mk
This ports over recent (and some future, namely https://github.com/stackrox/stackrox/pull/2650) changes to the `protogen.mk` protobuf build logic from stackrox/stackrox to scanner, with the aim of (a) staying up-to-date and (b) reducing divergence between the two.
=> Update protobuf tooling

scripts/ci/lib.sh
This makes it easier to find the tag for the images for periodic runs. I think just printing is fine. No need to put this in a Slack channel or anything
=> Print the tag CI pushes

.openshift-ci/Dockerfile.build_root, BUILD_IMAGE_VERSION, image/scanner/rhel/Dockerfile, image/scanner/rhel/Dockerfile.slim, pkg/rpm/database.go
1. Bump Scanner and Scanner Slim image to UBI9.
1. Re-build the rpm database when analyzing rpm packages.
The goal of (1.) is to get `rpm >= 4.16` to support RHEL9 scanning. The goal of (2.) is to ensure the rpm database format in the image is migrated to the latest to avoid issues with compatibility between the Scanner's rpm and the images'. In particular, Scanner's rpm (UBI9) only has `bdb_ro` mode enabled, [which doesn't support querying indexes in BDB-based databases](https://github.com/rpm-software-management/rpm/pull/1578).
- Local deployment (`make deploy`) followed by E2E tests.
- OCI Rehearsal: https://github.com/openshift/release/pull/31088
- CI
=> Bump Scanner to UBI9

api/grpc/grpc.go
`grpc.WithInsecure()` is deprecated. It is recommended to switch it with `grpc.WithTransportCredentials(insecure.NewCredentials())`. See https://pkg.go.dev/google.golang.org/grpc#WithInsecure.
=> Update insecure gRPC dial

.openshift-ci/build/Dockerfile.build-bundle, .openshift-ci/build/Dockerfile.build-db-bundle, .openshift-ci/build/Dockerfile.generate-db-dump, .openshift-ci/build/Dockerfile.generate-genesis-dump
Onboard UBI9 to all CI images by bumping the base image to the latest.
Relying on CI
=> Bump CI images to latest scanner-test-0.3.45

.openshift-ci/build/generate-db-dump.sh, scripts/ci/postgres.sh
Received a warning about using a UID out of range: `adduser warning: pg's uid 71 outside of the UID_MIN 1000 and UID_MAX 60000 range.`
This step fails on `initdb`, though, because it cannot find it in the path. That's because it's no longer in `/usr/bin` as it used to be. So, let's update the `PATH` used by the `pg` user. The error message is:
```
/go/src/github.com/stackrox/scanner/scripts/ci/postgres.sh: line 10: initdb: command not found
```
Also, forgot to source lib.sh in postgres.sh, so I can see `info: No menu item 'Starting Postgres' in node '(dir)Top'`
Tested this via the following:
1. `docker run -it quay.io/stackrox-io/apollo-ci:scanner-test-0.3.45 bash`
2. `git clone https://github.com/stackrox/scanner && cd scanner`
3. Update the .openshift-ci/build/generate-db-dump.sh to …
=> Update UID and PATH for generate-db-dump

api/v1/convert/k8s_convert_test.go, e2etests/node_scan_test.go, go.mod, go.sum, pkg/component/type.go, pkg/types/types.go
The https://github.com/stackrox/k8s-cves repo now adds the vulnerability's published time, so this PR is meant to ingest this data.
Tested with a local instance of StackRox using the Scanner version built from this PR and found the following:
=> ROX-12036: Add Kubernetes CVE published time

Makefile, image/db/rhel/Dockerfile, image/db/rhel/Dockerfile.slim, image/db/rhel/create-bundle.sh, image/scanner/rhel/create-bundle.sh
To test this, run `make image` on your MacBook with Apple silicon, and set the `SCANNER_IMAGE` and `SCANNER_DB_IMAGE` env variables to match the images built by `make`.
Then run `./deploy/k8s/deploy-local.sh` and check that scanner and scanner-db are running.
As a prerequisite, the main image has to be built locally as well, because we do not yet have arm64 images in the repository.
=> Enable local builds on M1 Macs with custom builder image

e2etests/testcase_test.go, pkg/features/list.go, pkg/rhelv2/rhelv2.go
This PR enables the RHEL9 feature flag and adds one minimal E2E test to exercise the feature.
Deployed Scanner locally and run the E2E.
=> ROX-11315: Enable RHEL9 scanning

.openshift-ci/runners.py
This will help us see why Scanner may fail to deploy in the pre-test
=> Always run OSCI post test

e2etests/grpc_full_test.go, e2etests/grpc_test.go, e2etests/sanity_test.go, e2etests/testcase_test.go, pkg/features/list.go
Disable RHEL9 scanning support. Leave E2E tests behind the feature flag.
Unfortunately, Red Hat ACS builds are tied to Stackrox, and currently, there are difficulties running the RHEL9 scanning code downstream. To not block downstream releases while we address the difficulties we are reverting back RHEL9 support to disabled.
=> ROX-11315: Disable RHEL9 scanning

e2etests/grpc_test.go, e2etests/testcase_test.go
E2E tests were panicking due to https://github.com/stackrox/scanner/blob/29bd3638e197a6bae24974b19b7d8f22111e3bb8/e2etests/grpc_test.go#L24, so removing that line, as it is not necessary.
Also, fixing the potential for running duplicate tests upon multiple calls to `getEnabledTestCases()`
=> fix E2E test panic and test duplication

chart/templates/db-deployment.yaml
Using the same resource specs as the `db` image. This is related to https://github.com/stackrox/stackrox/pull/2976
=> Add init-db resource specs for E2E tests

cmd/updater/diffdumps/cmd.go, k8s/cache/load.go, pkg/vulnloader/k8sloader/yaml.go
A malformed k8s vuln file can cause Scanner to halt all k8s vuln updates. This PR prevents this by simply logging the error and continuing.
Meanwhile, there is currently an issue with current live Scanner due to malformed k8s vuln files. This is because of how the published time is marshaled to JSON. To fix this, instead of requiring the JSON to be marshaled, we just copy the file contents directly over, as that is essentially what was already done anyway.
See https://go.dev/play/p/NCfVWO_AY5p?v=goprev to prove it is ok to unmarshal an empty file into a struct
=> ROX-12387: Prevent malformed k8s vuln update from hindering other k8s updates

pkg/matcher/matcher.go, pkg/matcher/matcher_test.go, singletons/requiredfilenames/matcher.go
Create singletons for two different types of "matcher" (O.S. features and active vulnerability), and add a new matcher interface called `PrefixMatcher` that offers a method to retrieve the list of directories to look for files.
Node scanning will exclusively use the O.S. matcher. And the list of directories will be used by the node scanner to determine which directories to walk and extract files from. This allows node scanning to be specific on the directories to walk and ignore the other files that are irrelevant during the extraction. Notice that, some analyzers (also known as detectors) do not have a deterministic set of files to scan, they look at prefixes, we still need to walk in directories. 
UT and CI
=> ROX-12238: Isolate O.S. matchers to re-use by node scanning

cmd/clair/config.go, cmd/clair/config_test.go, cmd/clair/main.go, localdev/main.go, pkg/analyzer/analyzer.go, pkg/analyzer/analyzertest/fake_file.go, pkg/analyzer/gem/analyzer_test.go, pkg/analyzer/nodes/node.go, pkg/analyzer/nodes/node_test.go, pkg/analyzer/nodes/testdata/rootfs-foo/etc/redhat-release, pkg/matcher/matcher.go, pkg/metrics/extractfiles.go, pkg/tarutil/tarutil.go, pkg/tarutil/tarutil_test.go, singletons/requiredfilenames/matcher.go, worker.go
This PR is built on top of https://github.com/stackrox/scanner/pull/904 (please filter commits in the diff for a narrowed view of the changes).
Add `Analyze()` to `pkg/analyzer/nodes`, including related changes to allow external packages (in particular, Compliance) to consume it. `node.Analyze` is built on the recently introduced interfaces added to `pkg/analyzer`, and re-uses `clair.DetectContentFromFile()`.
Other marginal changes:
- Move file size limits to the `analyzer` package.
- Add metrics for node scanning.
UTs.
Local validation, here's the code (omitting imports):
```
func main() {
components, err := nodes.Analyze("localhost", "/", true)
if err != nil {
panic(err)
}
s, err := json.MarshalIndent(components, "", "    ")
if err != nil {
panic(err)
}
fmt.Println(string(s))
}
```
Next …
=> ROX-12238: Add node analysis package

worker.go
Use an empty list of analyzers if language vulnerability feature is disabled.
=> Do not analyze language vulns unless the feature is enabled

localdev/main.go, pkg/analyzer/detection/detection.go, pkg/analyzer/detection/errors.go, pkg/analyzer/nodes/node.go, worker.go
As suggested by Cong in #911 this PR move the basic detection methods out of `stackrox/scanner` into a separate package below `pkg` (in this case, `pkg/analyzer/detection`).
=> Refactor common detection function to its own package

Makefile
Don't merge until after this release and may need to apply same changes downstream, but we don't need to dynamically link scanner and can just build it statically
=> Statically build scanner

pkg/analyzer/nodes/node.go, pkg/analyzer/nodes/node_test.go, pkg/metrics/extractfiles.go
Based on https://github.com/stackrox/scanner/pull/927, make updates from comments left on https://github.com/stackrox/scanner/pull/911 made after merge
=> Minor updates for #911

Makefile, scripts/ci/lib.sh, scripts/ci/logcheck/check-logs.sh
I noticed "hourly" CI runs are pushing images with the nightly tag. I think this is because we set `CIRCLE_TAG` to `git tag --sort=creatordate --contains | tail -1`. I think if there have not been any merges to the `master` branch since the nightly ran, then this will return a nightly tag. For example, running this on the `master` branch right now gave me `2.26-nightly-20220930`.
This PR removes `CIRCLE_JOB` and `CIRCLE_TAG` and replaces `CIRCLE_TAG` with `NIGHTLY_TAG`
=> fix tag used for hourly CI runs

ext/vulnsrc/rhel/rhel.go, pkg/clairify/clair/clair.go, pkg/clairify/client/client.go, pkg/httputil/httputil.go
Prefer consts within the `http` package (i.e. `http.MethodGet`) instead of specifying the string literal "GET".
=> Use http consts for HTTP methods

image/db/rhel/create-bundle.sh
This line was changed by mistake in https://github.com/stackrox/scanner/pull/874/
This PR is only reverting that change.
=> Pass correct arguments to tar when creating db bundle

scripts/ci/gke.sh, scripts/ci/lib.sh
#954 changed `ci_export()` to not use `cci-export()` which is required to persist state for CLUSTER_NAME and ZONE for e2e tests. The e2e tests failed on the original PR.
This PR reverts the change to `ci_export()`.
=> CI: Fix missing CLUSTER_NAME

scripts/ci/gate-jobs-config.json
This step should not run upon tag creation.
=> CI: gate "upload-db-dump" for tag

api/v1/imagescan/service.go, api/v1/nodescan/service.go, api/v1/orchestratorscan/service.go, api/v1/ping/service.go, api/v1/vulndefs/service.go
gRPC code generation generates `Unimplemented...` structs that return an unimplemented status code for all methods. This struct should be embedded in all gRPC service implementations. While this is not currently enforced, future gRPC code generator versions will make this mandatory (this behavior can be disabled, but it is not recommended; see [here](https://github.com/grpc/grpc-go/issues/3669) for a lengthy discussion on this matter with the clear verdict that gRPC authors see embedding of `Unimplemented..` as something that should always have been required).
Alas, this makes service type assertions ineffective, but that seems to be the pill to swallow.
(description copied from https://github.com/stackrox/stackrox/pull/3538)
=> Make gRPC service structs forward-compatible by embedding Unimplemented.. types

image/db/rhel/Dockerfile, image/db/rhel/Dockerfile.slim
Refs: https://stackoverflow.com/a/68217042/1387612
Tests: https://github.com/openshift/release/pull/32858
OSCI: https://github.com/openshift/release/pull/32848
=> ROX-10613: Use ubi-minimal for scanner-db

e2etests/testcase_test.go
E2E tests failing due to vuln updates, so this fixes it.
=> fix E2E tests based on vuln updates

cmd/updater/common/dump_utils.go, cmd/updater/diffdumps/cmd.go, cmd/updater/diffdumps/rhelv2_diff.go, cmd/updater/printstats/cmd.go, cpe/nvdtoolscache/db.go, cpe/nvdtoolscache/load.go, k8s/cache/db.go, k8s/cache/load.go, pkg/cache/cache.go, pkg/repo2cpe/mapping.go, pkg/vulndump/loader.go, pkg/ziputil/open.go, pkg/ziputil/open_test.go
Clears up any potential confusion about when Close is used/needed
=> Replace uses of *zip.ReadCloser with *zip.Reader when Close is not used

.openshift-ci/clusters.py, scripts/ci/gke.sh
Based on https://github.com/stackrox/stackrox/pull/3604
=> Bump GKE provisioning timeout

cmd/updater/diffdumps/cmd.go, cmd/updater/diffdumps/rhelv2_diff.go, image/scanner/dump/genesis_manifests.json
The changes relating to the diff step in https://github.com/stackrox/scanner/pull/928 caused RHELv2 updates to not work properly with older Scanner versions.
Older Scanner versions rely on `PackageInfos` to be populated. Genesis dumps no longer populate this field, and the diff converted each base dump's `PackageInfos` to `Packages`. Instead, we should have converted the new `Packages` to the old `PackageInfos` so older scanners would understand them properly.
Local Testing Steps:
1. Run `make build-updater`
2. Run `./bin/updater generate-dump --out-file test.zip`. This will generate the latest genesis dump with the latest vulnerabilities
3. Run `./test.sh` where `test.sh` is defined below
4. Confirm `PackageInfos` are populated the correct data. For example, you can unzip …
=> ROX-13435: fix RHELv2 updates

e2etests/testcase_test.go
I just accepted this to ensure the vulnerability was added to our data feed ASAP. I finally was able to do some analysis and we can remove this TODO.
=> Remove TODO in ubuntu:22.04 E2E test

Makefile, scripts/ci/lib.sh
https://github.com/stackrox/scanner/pull/954 ensured hourly CI runs are not tagged with "nightly"; however, that change caused releases to be tagged improperly (the tag is the "long" version).
This PR adds a `RELEASE_TAG` which does not use the "long" version is the CI build is discovered to be for a release tag.
These changes were already used to tag `2.27.2`. Please see the CI run for this commit: https://github.com/stackrox/scanner/commit/e365ba197d3e2a0e459cc40cf6d2a00e08226701
=> fix release tagging

pkg/repo2cpe/mapping_test.go, pkg/repo2cpe/testdata/repository-to-cpe.json
https://access.redhat.com/security/data/metrics/repository-to-cpe.json added a new field to the JSON. This PR simply ensures current live Scanners will be able to continue parsing the file correctly
=> test updated repository-to-cpe.json format

pkg/analyzer/nodes/node.go, pkg/fsutil/fsutil.go, pkg/fsutil/fsutil_test.go, pkg/ziputil/open.go
It is possible a symlink in a node references a file outside of the "root". It's possible the symlink is a path which attempts to link to a file outside the bounds of its own "root".
It should be noted that we should, perhaps, drop symlink support in favor of determining and reading the expected paths, directly. This fix is added in case this does not happen or it happens after a release in which this function may be used.
=> ROX-14035: only read file if within given root

Makefile, tools/linters/go.mod, tools/linters/go.sum
In the Makefile, we define a few binaries which we download. However, when using them, we may not have necessarily used the correct binary versions (they may have been pulled from the system instead). This PR ensures we use the freshly downloaded versions of the binaries. See https://github.com/stackrox/stackrox/blob/master/Makefile to see that the stackrox repo does it this way.
This PR also updates the version of `github.com/sourcegraph/go-diff` used by `golangci-lint`. See https://github.com/stackrox/stackrox/pull/4320 for more information.
=> update binaries used in Makefile

e2etests/node_scan_rhcos_test.go
This is a follow-up to #1004.
In the test case, we need a package that has high probability of being free from vulnerabilities because we assert on it to be recognized by scanner and have exactly 0 vulnerabilities.
In this PR, I replace the previously used `grep` by `tzdata` guesstimating that the chance of finding a vulnerability in the latter is lower than in the former.
On CI and locally with:
- `make image deploy-local`
- Opening a port-forward to scanner:8443
- Running `go test -tags e2e -timeout=10s -count=1 -v -run ^TestGRPCGetRHCOSNodeVulnerabilities$  github.com/stackrox/scanner/e2etests`
=> Improve e2e testcase for RHCOS

e2etests/testcase_test.go
See https://access.redhat.com/errata/RHSA-2022:9098 as to why this package's fixedby is updated
=> e2e: update jenkins-2-plugins fixed by

e2etests/testcase_test.go
This honestly doesn't happen this often...
Please see https://access.redhat.com/errata/RHSA-2023:0079 for information about the latest vulnerability which affects these packages.
This was caught by noticing the periodic CI runs on the master branch have been failing due to this update.
=> e2e: update FixedBy version of dotnet-runtime rpm packages

e2etests/testcase_test.go
Remove [CVE-2022-30945 ](https://access.redhat.com/security/cve/CVE-2022-30945) from the list of vuln matching quay.io/rhacs-eng/qa:ose-jenkins.
E2E tests started failing [(ull-ci-stackrox-scanner-master-e2e-tests/1613715170297647104)](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/stackrox_scanner/1053/pull-ci-stackrox-scanner-master-e2e-tests/1613715170297647104). My understanding the CVE-2022-30945 was affecting OCP 4 (only major version) but recently (Last Modified: January 12, 2023 at 10:04:36 PM UTC) the 4.8 OVAL was published with a more specific matching.
Waiting on CI.
=> Fix E2E: remove CVE-2022-30945 from qa:ose-jenkins

api/v1/nodescan/service.go, cmd/clair/main.go, e2etests/node_scan_rhcos_test.go
As a result of https://github.com/stackrox/scanner/pull/1053 we decided that `Analyze` will not provide CPEs but instead would include RHEL content sets. This PR adapts the `GetNodeVulnerabilities` to that change, so that content sets are translated to CPEs in Scanner.
=> Support RHEL content sets in a call to GetNodeVulnerabilities

e2etests/testcase_test.go, pkg/wellknownnamespaces/set.go
Added test and indication that scanning of Alpine v3.17 based images is supported
- No vulns existed in base packages for `3.17.0` - custom image w/ vuln created and scanned as detailed below
**Dockerfile:**
```dockerfile
FROM alpine:3.17.0
RUN echo "https://dl-cdn.alpinelinux.org/alpine/v3.3/main" >> /etc/apk/repositories && \
apk add --no-cache --repository https://dl-cdn.alpinelinux.org/alpine/3.3/main apache2=2.4.27-r1
```
Pushed to `quay.io/dcaravel/sandbox/alpine-apache2:latest`
**Temporary Test Case (added to temp branch in `e2etests/testcase_test.go`):**
```go
{
image:                   "quay.io/dcaravel/sandbox/alpine-apache2:latest",
registry:                "https://quay.io",
source:                  "NVD",
onlyCheckSpecifiedVulns: true,
namespace:               "alpine:v3.17", …
```
=> ROX-14459: Alpine 3.17 Support

pkg/analyzer/nodes/node.go, pkg/analyzer/nodes/node_test.go
Explicitly add `usr/share/buildinfo` to the list of directories to detect files in node scanning. UT added to cover the new directory.
In node scan, we hard-code the directories to look for files during detection. To detect content sets, we need to include `usr/share/buildinfo/content_manifests.json`, hence the addition.
- UT
- Openshift 4.12 cluster.
=> Add usr/share/buildinfo to node scan

pkg/analyzer/detection/detection.go, pkg/analyzer/detection/detection_test.go, pkg/osrelease/osrelease.go, pkg/osrelease/osrelease_test.go
Hardcode content sets and use standard CPE resolution logic to provide CPE info on older OpenShifts (4.7, 4.8, 4.9). Other versions are ignored, and no content sets are returned.
OpenShift 4.10 onwards provides `/root/content_manifests/*.json.` -- the manifest that lists repositories used to install packages in the O.S. used to find CPEs to match against OVAL. But OCP < 4.10 does not. Nevertheless, we can construct the content sets by hand by following the rules used by RHCOS itself. This will allow scanner to match vulnerabilities for OCP 4.7, 4.8 and 4.9.
- UTs
- Deployment to Openshift 4.9. Added a debug line to Compliance:
```
collection/nodeinventorizer: 2023/01/31 08:04:25.319831 nodeinventory.go:33: Debug: Content sets found under /host: [rhel-8-for-x86_64-baseos-eus-rpms__8_DOT_4 …
```
=> ROX-13107: Hardcode content sets in RHCOS 4.7 to 4.9

e2etests/grpc_full_test.go, e2etests/grpc_test.go, e2etests/sanity_test.go, e2etests/testcase_test.go, e2etests/utils_test.go, ext/featurefmt/apk/apk.go, ext/featurefmt/apk/apk_test.go
This change will enable scanner to show vulnerabilities for source package for alpine linux.
Added a new e2e openssl vuln test for this scenario.
=> Added fix for ROX-12979- Vulnerability scan doesn't include dependency libs

pkg/cpeutils/utils.go, pkg/cpeutils/utils_test.go
OpenShift 4.13 is now the max known OpenShift version.
This actually is not needed at this time, as the CPEs in the OVAL v2 feeds specify this for us; however, we still have this to protect from potential future OVAL v2 changes.
Currently, the OVAL v2 feed for unfixable OpenShift vulns give us CPEs of the form:
`cpe:/a:redhat:openshift:4.13`, but there were talks of changing it to `cpe:/a:redhat:openshift:4`. We have this variable to capture what we know to be the latest version of OpenShift in case this change happens...
=> Update max known OpenShift version to 4.13

api/v1/models.go, api/v1/models_rhelv2.go, api/v1/models_rhelv2_test.go
Allowlist `linux` and `kernel` packages when matching vulnerability when the namespace is RHCOS.
Scanner explicitly skips packages prefixed with "linux" or "kernel" to ensure kernel-related vulnerability packages are not reported, as they are irrelevant for images. This is not the case for nodes. We should ensure these are noticed in RHCOS nodes.
- UTs.
=> ROX-14288: Ensure Linux Kernel related packages are not skipped in RHCOS node scanning

pkg/analyzer/detection/detection.go, pkg/analyzer/detection/detection_test.go
Add missing content sets to the hard-coded list for RHCOS 4.7, 4.8, and 4.9.
The additional content sets were found after the following steps, which I would like reviewers to also perform for validity:
1. In the corp network, you can inspect the RHCOS source code to determine which RPM repositories were enabled during the build [on gitlab](https://gitlab.cee.redhat.com/coreos/redhat-coreos/).
2. For each of the branches: 4.7, 4.8 and 4.9:
1. Open all the `*.repo` files.
2. For each repository, confirm the content set:
a. Open https://www.redhat.com/security/data/metrics/repository-to-cpe.json
b. Replace the architecture with `x86_64`, and grep for the repository path.
c. Copy the content set name for the entry found.
Notice that for 4.7, `advanced-virt-for-rhel-8-x86_64-eus-rpms` is not …
=> ROX-13107: Add missing content sets to the hard coded list for RHCOS 4.7, 4.8 and 4.9.

api/v1/nodescan/service.go, chart/templates/deployment.yaml, e2etests/node_scan_rhcos_test.go, pkg/env/list.go, pkg/features/list.go
Currently Scanner does not run v1 Node Scan when RHCOS is detected. It displays the following warning when Node Scanning is run on RHCOS:
This is by design as the v1 scan data from NVD was inaccurate and lead to confusion of users.
The goal of this ticket is to disable v1 Node Scan when RHCOS is detected and provide v2 scan instead.
This contains:
- remove the quit-early branch if RHCOS is detected
- do not run v1 scan if and only if: 
- (1) the FF is enabled, 
- (2) node inventory is present, 
- (3) RHCOS system is detected. (Note that 2 implies 3).
- ⚠️ I needed to skip the existing e2e tests if the feature flag it disabled. Otherwise they fail. I know this isn't great, but if someone knows a solution to enabling the FF in the e2e tests, then please let me know. 
```
$ go test -tags e2e …
```
=> ROX-14592: Ensure that RHCOS Node scan is not skipped by Scanner

api/v1/models_rhelv2_test.go
assert.Equalf works iff the order is the same. Use  assert.ElementsMatchf so we don't have to care about the ordering
=> Test_getFullRHELv2Features compare slices with assert.ElementsMatchf

e2etests/node_scan_rhcos_test.go, e2etests/testcase_test.go
Update to latest vuln data. Change RHCOS E2E assertion to show diffs when comparing vulns.
Our E2E tests rely on live vulnerability data that can change with time. In this case two changes happened:
1. https://access.redhat.com/errata/RHSA-2023:0560 was issued on 2023-02-08 affecting `jenkins-2-plugins`, that changed the `fixedBy` version of the package/feature -- it was bumped to a later version that fixes the mentioned RHSA.
2. https://access.redhat.com/errata/RHSA-2022:7089 has CVSS score data updated.
The changes to assertion were done to help identifying changes in future failures.
CI is green.
=> fix: Update E2E test after changes in vulnerability data

go.mod, go.sum
This is a follow up on https://github.com/stackrox/nvdtools/pull/8
When numeric parts are compared, 0's are padded to the left to ensure they have the same length. When all components are the same, the code relies on the string length, but the padded zeros are ignored, resulting in incorrect results.
CI
=> ROX-15044: Bump nvtools to fix NVD CPE version padded with zeros

ext/vulnsrc/rhel/rhel.go
The "genesis-dump" logs are riddled with this log everywhere. Let's just ignore this criterion, as it doesn't help us out, and it not an actual issue.
=> Ignore "Red Hat Enterprise Linux must be installed" criterion in RHELv1

e2etests/orchestrator_scan_test.go
E2E is failing because the number of expected fixed vulns for Openshift 4.7 has changed. The current fix bumps the max patch release to the latest and expects all remaining vulns to be fixed. Also, add a log line to help debug the issue in future failures.
The test bumps the patch version and tracks which vulnerabilities were fixed between them. Ultimately, it accounts for the total number of vulnerabilities fixed against the original value and expects the total to be lower.
The actual reason why the number of vulnerabilities changed is currently unknown to me.
Before the fix, these were the remaining vulns:
```
=== RUN   TestGRPCGetOpenShiftVulnerabilities/case-4.7
orchestrator_scan_test.go:146: Remaining vulns at 4.7.4:
orchestrator_scan_test.go:148: - "RHBA-2021:2979" (FixedBy: 4.7.23) …
```
=> Fix 4.7 known fixed vulns and max patch

pkg/nodeinventory/inventorizer.go
This PR follows up on #1118 , which, after merging, could not update the calls to `Analyze()` in inventories. The outdated calls broke master.
Waiting on CI.
=> Add context.Background() to Analyze() in inventorizer

api/v1/nodescan/service.go, pkg/analyzer/nodes/node_test.go
Set the operating system namespace in the `GetNodeVulnerabilities` response based on the scanned namespace.
Before, in "V1 node scanning" (aka. legacy node scanning), the namespace was determined from the Operating System Image name. But host-level scanning detects the "scanned namespace" in the node itself during node analysis. That namespace should be the authoritative string.
The [scan operating system](https://github.com/stackrox/stackrox/blob/62d79bce3df1d0bc689ea500b144b9a445da4b63/pkg/scanners/clairify/convert.go#L93-L92) is pulled from this. Since it's empty, the components list is missing "Operating System" column:
CI.
Deploy to `jvdm-argilo`:
=> Set the OS from the scanned namespace

.github/dependabot.yml
We can use dependabot to keep our actions up-to-date, so let's do it.
See https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot for more information about it.
=> dependabot update actions

pkg/features/list.go
This PR enables the feature flag for RHCOS node scanning.
=> ROX-13935: Enable RHCOS FF

api/grpc/grpc.go, go.mod
Dependabot made a PR #1138 to update that `grpc-middlware` but CI was failing because the new version deprecated `grpcmiddleware .WithUnaryServerChain` in favor of `grpc.ChainUnaryInterceptor`. This PR makes this replacement.
See https://pkg.go.dev/github.com/grpc-ecosystem/go-grpc-middleware#WithUnaryServerChain for more information.
=> remove grpc-middleware direct dependency

api/v1/nodeinventory/service.go, pkg/analyzer/detection/detection.go, pkg/analyzer/nodes/node.go, pkg/nodeinventory/inventorizer.go
This PR rephrases log messages concerning RHCOS, so that they are:
- not polluting the logs too much
- more informative
This is a sister-PR for https://github.com/stackrox/stackrox/pull/5469
=> ROX-14358: Ensure RHCOS logging is informative

api/v1/imagescan/service.go, e2etests/testcase_test.go
GRPC Invocations of `GetImageComponents` (`proto/scanner/api/v1/image_scan_service.proto`) will fail with a `NotFound` error if the request contains a digest the represents a `ManifestList` (observed during testing of on-prem local registry scanning)
This change ensures that the digest passed in the request is also used when obtaining layer data
See [ROX-16310](https://issues.redhat.com/browse/ROX-16310) for more details
=> ROX-16310 - Fix GetImageComponents ManifestList Not Found

e2etests/testcase_test.go, go.mod, go.sum, pkg/clairify/types/types.go, pkg/scan/scan.go
Scanner does not currently support images with manifest media type `application/vnd.oci.image.index.v1+json`. This PR adds this support by bumping the docker-registry-client library version which adds this support as well as adding a handler for this manifest type.
See https://github.com/stackrox/scanner/pull/1155 for proof this was not supported prior to this PR.
=> ROX-16421: support OCI image index media type

e2etests/testcase_test.go
Updating FixedBy to fix CI error(s):
```
{Failed      sanity_test.go:126: 
Error Trace:	/go/src/github.com/stackrox/scanner/e2etests/sanity_test.go:126
Error:      	Not equal: 
expected: v1.Feature{Name:"jenkins-2-plugins", NamespaceName:"rhel:8", VersionFormat:"rpm", Version:"4.10.1650890594-1.el8.noarch", Vulnerabilities:[]v1.Vulnerability(nil), AddedBy:"sha256:3fa3f612bdcb92746bf76be1b9c9e1c1c80de777aedaf48b7068f4a129ded3c2", Location:"", FixedBy:"4.10.1680703106-1.el8", Executables:[]*scannerV1.Executable(nil)}
actual  : v1.Feature{Name:"jenkins-2-plugins", NamespaceName:"rhel:8", VersionFormat:"rpm", Version:"4.10.1650890594-1.el8.noarch", Vulnerabilities:[]v1.Vulnerability(nil), AddedBy:"sha256:3fa3f612bdcb92746bf76be1b9c9e1c1c80de777aedaf48b7068f4a129ded3c2", Location:"", …
```
=> Update e2e Jenkins FixedBy version to 4.10.1681719745-1.el8

.github/dependabot.yml
`stackrox/scanner-dep-updaters` is deprecated in favor of `stackrox/scanner`
=> update dependabot reviewers to scanner team

e2etests/testcase_test.go
Our E2E tests rely on live vulnerability data that can change with time. Some RHSA (I believe https://access.redhat.com/errata/RHSA-2023:3362) was issued that affected `jenkins-2-plugins`, changing the expected `fixedBy` version of the package/feature -- it was bumped to a later version that fixes the mentioned CVE (https://access.redhat.com/security/cve/CVE-2023-1370).
```
{Failed      grpc_full_test.go:102: 
Error Trace:	/go/src/github.com/stackrox/scanner/e2etests/grpc_full_test.go:102
Error:      	Not equal: 
expected: scannerV1.Feature{Name:"jenkins-2-plugins", Version:"4.10.1650890594-1.el8.noarch", FeatureType:"rpm", AddedByLayer:"sha256:3fa3f612bdcb92746bf76be1b9c9e1c1c80de777aedaf48b7068f4a129ded3c2", Location:"", Vulnerabilities:[]*scannerV1.Vulnerability(nil), …
```
=> fix: Expected fixedby version for jenkins-2-plugins

e2etests/testcase_test.go
Update fixed by versions for `dotnet-runtime-6.0` and `aspnetcore-runtime-6.0` due to https://access.redhat.com/errata/RHSA-2023:3582
CI failures:
```
github.com/stackrox/scanner/e2etests: TestImageSanity/quay.io/rhacs-eng/qa:sandbox-dotnet-60-runtime-6.0-15.20220620151726/aspnetcore-runtime-6.0/6.0.6-1.el8_6.x86_64 expand_less | 0s
{Failed      sanity_test.go:126: 
Error Trace:	/go/src/github.com/stackrox/scanner/e2etests/sanity_test.go:126
Error:      	Not equal: 
expected: v1.Feature{Name:"aspnetcore-runtime-6.0", NamespaceName:"rhel:8", VersionFormat:"rpm", Version:"6.0.6-1.el8_6.x86_64", Vulnerabilities:[]v1.Vulnerability(nil), AddedBy:"sha256:16e1dc59de605089610e3be2c77f3cde5eed99b523a0d7a3e3a2f65fa7c60723", Location:"", FixedBy:"6.0.13-1.el8_7", …
```
=> fix: Expected fixedby version for `sandbox-dotnet-60-runtime`

e2etests/grpc_full_test.go, e2etests/testcase_test.go
Add a custom assertion message pointing out which potential vulnerabilities bumped up the FixedBy, so we can check if a bump in the test is necessary or if it's a bug in FixedBy logic.
CI.
=> Improve FixedBy assertion

e2etests/testcase_test.go, pkg/analyzer/java/parse_manifest_test.go, pkg/analyzer/java/parse_manifests.go
So we don't stop early if we have matched all the possible key lines in the manifest.mf file. This file can contain many entries and this will cause us to attribute the data to a wrong version
=> ROX-17114: Fix misattribution of Java versions when there are multiple matching lines

database/pgsql/migrations/00020_languagelayer_lineage_pk.go, e2etests/vuln_test.go
The issue was laid out in the doc by David. Basically what's happening is that the sample images have layers that are identical so they have the same "layer_name" which is the digest, but the lineage is different. This means that if you have identical layers with vulns that have different lineages (or parent layers) then the second insertion is due to the conflict on the layer_name (insert does on conflict do nothing). This change makes it so that table is keyed on layer_name and lineage, effectively only deduping layers with the exact same parents (which is good because we don't need to reinsert the layers). The unit test should test this case
~Note: for some reason, this does not work on scratch, but I find that less pressing because it seems to be when the language vuln is simply in …
=> ROX-18202: Fix language layer error due to unique constraint

e2etests/testcase_test.go
anchore-engine:
This image is affected by CVE-2023-4016. The CVE page says "Out of Support" but it's still vulnerable. The id in the OVAL feed is `oval:com.redhat.cve:def:20234016`, which indicates a vulnerability.
Originally, I was going to add that vulnerability to the list, but the description used some special formatting which seemed annoying to mimic, so I decided to just not check for that vulnerability. Adding this vulnerability did not really add much value anyway
=> e2e: misc test updates

api/v1/nodescan/service.go, chart/templates/deployment.yaml, pkg/features/list.go
This PR removes the RHCOS Node Scanning Feature Flag, as we have not experienced any issues or instabilities with running the feature.
=> ROX-19024: Remove RHCOS FF

e2etests/testcase_test.go
Due to RHSA-2023:5144 fixed by bumped to 6.0.22-1.el8_8 E2E tests are failing, and this fixes it.
=> fix(scanner): Fix dotnet-runtime-6.0 latest FixedBy

pkg/rhelv2/rpm/rpm.go
Noticed this when doing https://github.com/stackrox/scanner/pull/1263.
`contentManifestDirs` was empty in the `init()` call to `RequiredFilenames()`. This PR fixes that.
=> fix: reorder rhelv2 required files

ext/featurens/osrelease/osrelease.go, ext/featurens/osrelease/osrelease_test.go, ext/featurens/redhatrelease/redhatrelease.go, ext/featurens/redhatrelease/redhatrelease_test.go, pkg/osrelease/osrelease.go
It is possible an official Red Hat container image has `etc/redhat-release` as a symlink to `usr/lib/redhat-release` instead of being a regular file. This PR adds `usr/lib/redhat-release` as a file to track.
It also updates the `etc/os-release` support for RHEL/CentOS in case there may be some other case we miss. The update ensures only the major version of the release is returned when reading a RHEL or CentOS namespace from `etc/os-release`.
=> ROX-19942: support usr/lib/redhat-release and RHEL Atomic Host release

pkg/vulnloader/nvdloader/manual.go
I ran a genesis dump without these changes (see https://github.com/stackrox/scanner/pull/1276). You'll notice in that PR in the genesis dump logs, you will find logs saying CVE-2023-38545 and CVE-2023-38546 are missing for several distributions. With this PR, they are no longer missing, as we utilize the CVSSv3 scores from our "NVD" manual entries.
Note: this does not affect Red Hat, as they track CVSS scores, themselves
=> vulns: add curl and libcurl vulns

go.mod, go.sum
Bump go-grpc to 1.58.3, which fixes [CVE-2023-44487](https://github.com/advisories/GHSA-qppj-fm5r-hxr3) for the gRPC server.
=> ROX-20122: bump go-gprc to 1.58.3

api/grpc/grpc.go, pkg/env/list.go
As part of the mitigation for [cve-2023-44487](https://access.redhat.com/security/cve/cve-2023-44487), some projects have decided to reduce MaxConcurrentStreams to 100 (this is the minimum recommended value in the HTTP/2 standard - default is 250).
This PR applies this change to the Scanner gRPC server.
=> ROX-20122: set gRPC max concurrent streams to 100

api/grpc/grpc.go, pkg/env/integersetting.go, pkg/env/list.go
- chore: allow integer env vars (#1289)
- ROX-20121: set gRPC max concurrent streams to 100 (#1287)
=> ROX-20121: set gRPC max concurrent streams to 100

pkg/clairify/metrics/server.go, pkg/clairify/server/server.go
disallow HTTP/2 for the metrics server, as it's not required.
=> http(metrics): disallow auto HTTP/2 enablement

e2etests/grpc_full_test.go, e2etests/sanity_test.go
It would be nice to know which vulns were found in this case so we can get a better idea of what Scanner found.
This is added due to Scanner intermittently not finding CVE-2021-26291 for jenkins-2-plugins
=> e2e: improve logging

.openshift-ci/Dockerfile.build_root, .openshift-ci/build/Dockerfile.build-bundle, .openshift-ci/build/Dockerfile.build-db-bundle, .openshift-ci/build/Dockerfile.generate-db-dump, .openshift-ci/build/Dockerfile.generate-genesis-dump, BUILD_IMAGE_VERSION
See https://github.com/stackrox/scanner/pull/1181 for how Go version bump was previously done
See https://github.com/stackrox/rox-ci-image/releases/tag/0.3.61 for what's new in this CI image
=> go: bump go to 1.20.10

pkg/cpeutils/utils.go, pkg/cpeutils/utils_test.go
OpenShift 4.14 went GA, so we need to make sure we can find all vulns for it. This codepath is not used at this time, but it's possible it would be needed were the OpenShift CPE changed. It is here for that safety.
=> chore: account for OpenShift 4.14

.openshift-ci/build/build-bundle.sh, .openshift-ci/build/build-db-bundle.sh, .openshift-ci/build/generate-db-dump.sh, .openshift-ci/build/generate-genesis-dump.sh, .openshift-ci/dispatch.sh, .openshift-ci/nightlies.sh, scripts/ci/deploy.sh, scripts/ci/gcp.sh, scripts/ci/gke.sh, scripts/ci/jobs/db-integration-tests.sh, scripts/ci/jobs/diff-dumps.sh, scripts/ci/jobs/e2etests/e2e-tests.sh, scripts/ci/jobs/e2etests/scale-tests.sh, scripts/ci/jobs/e2etests/slim-e2e-tests.sh, scripts/ci/jobs/push-images.sh, scripts/ci/jobs/sanity-check-vuln-updates.sh, scripts/ci/jobs/store-db-dump.sh, scripts/ci/jobs/store-genesis-dump.sh, scripts/ci/jobs/style-checks.sh, scripts/ci/jobs/unit-tests.sh, scripts/ci/jobs/upload-db-dump.sh, scripts/ci/jobs/upload-dumps-for-downstream.sh, scripts/ci/jobs/upload-dumps-for-embedding.sh, scripts/ci/lib.sh, scripts/ci/logcheck/check-logs.sh, scripts/ci/postgres.sh, scripts/ci/store-artifacts.sh
These changes fix [shellcheck 1091](https://www.shellcheck.net/wiki/SC1091) for all scripts. An important side effect is you can use the Bash LSP to go to functions in scripts.
You can check all `.sh` files that violate SC1091 using the following command:
```sh
find . -type f -name "*.sh" -execdir shellcheck -i SC1091 -P SCRIPTDIR -x {} \;
```
No violations appear after these changes.
=> chore: fix shellcheck 1091 for all scripts

pkg/vulndump/batch_loader.go, pkg/vulndump/batch_loader_test.go, pkg/vulndump/loader.go, pkg/vulndump/loader_test.go
```
$ go test -run=^$ -bench=^BenchmarkLoadOSVulnsFromDump$ -benchmem ./pkg/vulndump/
goos: darwin
goarch: amd64
pkg: github.com/stackrox/scanner/pkg/vulndump
cpu: Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
BenchmarkLoadOSVulnsFromDump-8   	       1	4358242218 ns/op	1314951824 B/o 8285803 allocs/op
--- BENCH: BenchmarkLoadOSVulnsFromDump-8
loader_test.go:26: Loaded 134043 vulns
PASS
ok  	github.com/stackrox/scanner/pkg/vulndump	5.990s
$ go test -run=^$ -bench=^BenchmarkOSLoader$ -benchmem ./pkg/vulndump/
goos: darwin
goarch: amd64
pkg: github.com/stackrox/scanner/pkg/vulndump
cpu: Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
BenchmarkOSLoader-8   	       1	4075758627 ns/op	702698568 B/op	 8285718 allocs/op
--- BENCH: BenchmarkOSLoader-8
batch_loader_test.go:57: Loaded 134043 vulns
PASS
ok …
```
=> ROX-21387: batch insert vulns

e2etests/testcase_test.go
Fix the test in scanning package:
"Name": "jackson-databind",
"VersionFormat": "JavaSourceType",
"Version": "2.9.10.4"
=> fix test on package jackson-databind 2.9.10.4

cmd/clair/main.go
Increase the number of DB connection retries before exiting to be a total of 5 minutes (up from 3 minutes).
--
CI jobs will report failure if a scanner pod restarts, and scanner will exit/restart after 3 minutes currently 
`18 retries * 10 seconds = 180 seconds = 3 minutes`
A [previous CI failure](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-stackrox-stackrox-master-merge-gke-version-compatibility-tests/1732544504176578560) showed the database available 1 minutes after scanner had exited.
Increasing retries should reduce the frequency of CI failures due to pod restarts.
`30 retries * 10 seconds = 300 seconds = 5 minutes`
=> ROX-21319: Increase DB connection retries

image/db/rhel/Dockerfile, image/db/rhel/Dockerfile.slim
Scanner DB stopped building. Not sure when it started, but I noticed it today. The issue is Postgres moved the location of the GPG key. This PR updates the URL used to download the GPG key
=> chore(scanner-db): update GPG key link

.github/workflows/ci.yaml
https://github.com/stackrox/scanner/pull/1373 and https://github.com/stackrox/scanner/pull/1374 need to be in the same PR.
=> Update artifact actions in GHA

scripts/ci/jobs/diff-dumps.sh
Generate scanner-vulns-{version}.zip for scanner v4 offline mode
Due to time constraints and my limited understanding of decoupling ci.yaml and diff-dump (just for testing), I directly modified the diff-dump.sh script.
=> Generate v4 versioned offline vuln

.github/workflows/ci.yaml, scripts/ci/jobs/diff-dumps.sh
Generate scanner-vuln-update including v4 vulnerability of latest version
Currently I can only verify scanner v2 work with new **_scanner-vuln-updates.zip_**, more V4 related tests will be done in ROX-21981
1. Make sure the zip is containing scanner v4 stuff:
```
ls -lh scanner-vuln-updates.zip 
-rw-r--r-- 1 yili staff 272M Feb 14 15:04 scanner-vuln-updates.zip
```
```
unzip -l scanner-vuln-updates.zip
Archive:  scanner-vuln-updates.zip
Length      Date    Time    Name
---------  ---------- -----   ----
140154404  02-14-2024 11:41   scanner-defs.zip
248088  02-14-2024 11:41   k8s-istio.zip
144211510  02-14-2024 11:41   scanner-v4-defs-4.3.zip
---------                     -------
284614002                     3 files
```
2. Upload to Central:
```
yli3-mac:stackrox yili$ curl --insecure -u …
```
=> Include latest v4 vulnerability

.tekton/scanner-db-pull-request.yaml, .tekton/scanner-db-push.yaml, .tekton/scanner-db-slim-pull-request.yaml, .tekton/scanner-db-slim-push.yaml, .tekton/scanner-pull-request.yaml, .tekton/scanner-push.yaml, .tekton/scanner-slim-pull-request.yaml, .tekton/scanner-slim-push.yaml
The overrides are possible after https://issues.redhat.com/browse/PLNSRVCE-1625 got addressed.
I did not go over OOTB limits, rather made requests high enough so that CPU is actually reserved for intensive steps when Konflux cluster is oversubscribed. However, we can redefine limits too if needed.
I did not override cpu for scanner-db* builds because there's no lengthy Go compilation. I hope the default 250m should be enough, or we'll see.
My idea for this PR is to have the feature enabled to assess its stability and usefulness for us should we observe the need to tweak requests.
This reinstates <https://github.com/stackrox/scanner/pull/1394>.
The commit history (at the time of publishing) is messy. It only makes sense to review the final state (i.e. not per commit).
=> chore: Override `cpu` `requests` for bad days in Konflux

go.mod, go.sum
Let's use fork that is in the org instead of private one.
- https://github.com/stackrox/stackrox/pull/10373
=> chore(deps): use stackrox fork of gogo

.github/workflows/ci.yaml, .openshift-ci/Dockerfile.build_root, .openshift-ci/build/Dockerfile.build-bundle, .openshift-ci/build/Dockerfile.build-db-bundle, .openshift-ci/build/Dockerfile.generate-db-dump, .openshift-ci/build/Dockerfile.generate-genesis-dump, BUILD_IMAGE_VERSION, image/db/rhel/Dockerfile, image/db/rhel/Dockerfile.slim, image/db/rhel/konflux.Dockerfile, image/db/rhel/scripts/docker-entrypoint.sh
See for related changes: https://github.com/stackrox/rox-ci-image/pull/198
DB integration tests run in a GitHub Workflow, so it should be using PostgreSQL 15. If not, I also tested it locally by running `make db-integration-tests` while running a PostgreSQL 15 server in the background.
=> ROX-22044: postgresql 15

.github/workflows/ci.yaml, scripts/ci/jobs/diff-dumps.sh
The diff zips generated by the `diff-dumps` job for a PR with label "generate-dumps-on-pr" are not made accessible for inspection ([example run](https://github.com/stackrox/scanner/actions/runs/8608350848/job/23591361309?pr=1464)).
These changes add `diff-dumps` to the GitHub Actions artifacts.
=> ROX-23563: Add diff-dumps to GHA artifacts

pkg/env/list.go, pkg/mtls/verifier.go, pkg/mtls/verifier_test.go
Adjusts the Scanner mTLS configuration to allow requests from Sensor irregardless of the k8s flavor.
This is necessary to support delegated scanning in non-OCP environments where Central/Sensor exist in same namespace.
Also removes references to `ROX_OPENSHIFT_API` that are no longer used.
This is a two part change, also refer to: https://github.com/stackrox/stackrox/pull/10759
Created a gke infra cluster, installed ACS into a single namespace (with the net policy changes referenced in the [other PR](https://github.com/stackrox/stackrox/pull/10759)), and delegated scans.
Before this change:
```
$ rctl image scan --image=nginx:1.13.0 --cluster=remote
ERROR:	Scanning image failed: could not scan image: "nginx:1.13.0": rpc error: code = Internal desc = error delegating scan to cluster …
```
=> ROX-21744: allow sensor/scanner comms in non-ocp (2/2)

go.mod, go.sum
Fixed a potential panic and created the first release of this: v0.1.0
https://github.com/stackrox/docker-registry-client/pull/19
I also tried to remove the `replace`, but the circular dependency with the stackrox/stackrox repo made this super annoying. Would rather just deal with this, since we don't expect this to update much, and we plan on removing this repo as a dependency for stackrox/stackrox in the future, anyway
=> chore(deps): bump docker-registry-client

image/scanner/dump/genesis_manifests.json
Changes were made to the OVAL data that scanner currently cannot handle via the regular diff dumps (packages were removed from a vuln without an associated advisory)
A new genesis dump is needed to bring in the changes, targeting the next ACS patch release(s).
=> ROX-22889: Create new genesis dump 

.tekton/determine-image-tag-task.yaml, .tekton/scanner-db-pull-request.yaml, .tekton/scanner-db-push.yaml, .tekton/scanner-db-slim-pull-request.yaml, .tekton/scanner-db-slim-push.yaml, .tekton/scanner-pull-request.yaml, .tekton/scanner-push.yaml, .tekton/scanner-slim-pull-request.yaml, .tekton/scanner-slim-push.yaml
According to https://github.com/stackrox/stackrox/pull/10749.
Produces images like `quay.io/redhat-user-workloads/rh-acs-tenant/acs/scanner-slim:2.33.x-57-gc4ce126d08-fast`.
=> ROX-24081: use make tag result in image names on Konflux

.tekton/scanner-db-pull-request.yaml, .tekton/scanner-db-push.yaml, .tekton/scanner-db-slim-pull-request.yaml, .tekton/scanner-db-slim-push.yaml, .tekton/scanner-pull-request.yaml, .tekton/scanner-push.yaml, .tekton/scanner-slim-pull-request.yaml, .tekton/scanner-slim-push.yaml
Produced: `quay.io/rhacs-eng/2.33.x-60-gfb93da2520-fast` and corresponding source and attribution images.
=> ROX-22474: push Konflux images to quay.io/rhacs-eng

.tekton/scanner-component-pipeline.yaml, Makefile, image/db/rhel/konflux.Dockerfile, image/scanner/rhel/konflux.Dockerfile
When looking at collector (<https://github.com/stackrox/collector/pull/1694>), I realized I did a bit of mess in my earlier <https://github.com/stackrox/scanner/pull/1527>.
Here I get rid of `TAG_SUFFIX` variable and inject the full tag via `RELEASE_TAG` environment variable. See
https://github.com/stackrox/scanner/blob/631dea9898c3c69f18ea3c45dd66e733cd616905/Makefile#L13-L21
I also inject a value into the `version` label in all four built containers. Similar to <https://github.com/stackrox/collector/pull/1694>, if/when we'll need to re-tag, we will take care of the label then. Mentioned that in ROX-24468.
Testing:
For the last item, smoke-tested build, seeing proper thing in logs:
```
{"Event":"Running Scanner version: 2.33.x-80-gc60f8fc954-fast","Level":"info","Location":"main.go:293"," …
```
=> chore: Swap `TAG_SUFFIX` for `SCANNER_TAG`

scripts/ci/gke.sh
If you're really unlucky, you can get a `.` at the end of the `tags` variable, which will be substituted for `-` _after_ we replace the last `-` with `x`.  GKE doesn't allow for `-` at the end of the string, which is why we change the last `-`.
See https://github.com/openshift/release/pull/47789 for a real-world example of this problem.
These changes reorders the shell expansion so we first replace all `.` with `-`, _then_ delete the last `-`.
Port from https://github.com/stackrox/stackrox/pull/11160
Testing the variable expansions:
```sh
❯ JOB_NAME=rehearse-47789-pull-ci-stackrox-scanner-release-2.32-e2e-tests
❯ tags="stackrox-ci"
❯ tags="${tags},stackrox-ci-${JOB_NAME:0:50}"
❯ echo "${tags}"
stackrox-ci,stackrox-ci-rehearse-47789-pull-ci-stackrox-scanner-release-2.
❯ tags="${tags/%-/x}" …
```
=> fix(ci): reorder gke tags and labels variable expansions

image/db/rhel/Dockerfile, image/db/rhel/Dockerfile.slim, image/db/rhel/konflux.Dockerfile
There's no need to own executable by `postgres` user, hence removed `chown`.
There's no need to add executable flag because `COPY` statement preserves it and the original file has it, hence removed `chmod`.
=> ROX-20855: Reduce container user permissions over `docker-entrypoint.sh`

image/db/rhel/konflux.Dockerfile, image/scanner/rhel/konflux.Dockerfile
=> ROX-20236: Set `release` Dockerfile label explicitly

go.mod, go.sum
github.com/mholt/archiver/v3 v3.51.1 is affected by CVE-2024-0406. There is a [PR in-progress](https://github.com/mholt/archiver/pull/396) to resolve this, but it has been rather inactive lately.
We are not affected by this vulnerability, as it affects a codepath which we do not use.
I previously decided to remove the https://github.com/stackrox/scanner/pull/1472 dependency by copying functions over to this repository. However, I ran into issues with CI I have not really been wanting to resolve in that PR, and I believe this approach is safer.
In this approach, we replace github.com/mholt/archiver/v3 v3.51.1 with github.com/anchore/archiver/v3 v3.51.2. See https://github.com/mholt/archiver/compare/v3.5.1...anchore:archiver:v3.5.2 for the exact details. It is clear the only difference is …
=> fix(deps): switch to github.com/anchore/archiver/v3

.github/workflows/ci.yaml
These changes enable GitHub Action workflows for jobs that were previously running in OSCI. Once merged, any new tags containing these changes will have OSCI configs that look more like master's than the other release branch OSCI configs.
Note for reviewers: here's the OSCI config that gates certain jobs from running in certain contexts: https://github.com/stackrox/scanner/blob/master/scripts/ci/gate-jobs-config.json. We should generally try to follow this for now unless we see a compelling reason not to.
=> ROX-21124: Move release branch jobs from OSCI to GHA

.github/workflows/ci.yaml
If you pull `quay.io/stackrox-io/vulnerabilities:latest` right now and check for the vulnerability data, you'll notice the zip file is located at `/srv/scanner-vuln-updates.zip/scanner-vuln-updates.zip`. These changes remove the `scanner-vuln-updates.zip` directory, so the location should be `/srv/scanner-vuln-updates.zip`.
=> fix: remove directory name duplication in vulnerability data image

e2etests/testcase_test.go
Fixes the `TestGRPCGetImageVulnerabilities/quay.io/rhacs-eng/qa:ubuntu-22.04-openssl/openssl/3.0.2-0ubuntu1.6` E2E test.
=> chore(e2e): fix Ubuntu openssl test

README.md, pkg/wellknownnamespaces/set.go
Debian 10 is no longer supported, so move into the stale state. Debian 10 vulns were uploaded to the StackRox GCS bucket
=> chore: update status of Debian 10

.github/workflows/ci.yaml, pkg/env/list.go, pkg/vulnloader/nvdloader/loader.go, pkg/vulnloader/nvdloader/loader_legacy.go
Revives the old NVD loader that pulls from the NVD legacy feeds, and makes it configurable.
The code was largely copied from the version just before this PR: https://github.com/stackrox/scanner/pull/1329 with the following changes:
- Moved methods into a new `legacyLoader` (instead of package level) to avoid conflicts with the NVD 2.0 API `loader`
- Added the `ROX_LEGACY_NVD_LOADER` env var that when `true` will cause the legacy loader to be used, otherwise the NVD 2.0 loader. 
Ran updater locally:
_output trimmed for brevity_
```
$ ./bin/updater generate-dump --out-file image/scanner/dump/dump.zip
INFO[0000] Using temp dir "/var/folders/5n/r7z59gz16v98qlf3mb_d3_gh0000gn/T/vuln-updater3499419215" for scratch space 
INFO[0000] Downloading istio...                         
INFO[0000] …
```
=> chore: revive legacy NVD feed and make toggleable

image/scanner/dump/genesis_manifests.json
Based of the dump from this run: https://github.com/stackrox/scanner/actions/runs/9810783119
=> chore: update genesis dump targeting scanner 2.34 (acs 4.5.0)

.github/actions/handle-tagged-build/action.yaml, .github/workflows/ci.yaml, scripts/ci/lib.sh
Our `tag` make target relies on the `RELEASE_TAG` environment variable being set to the tag name when we perform a release build. Many of our scripts and processes rely on `make tag` outputting the current string (like the release version). We used to set this environment variable properly in OSCI due to:
https://github.com/stackrox/scanner/blob/372710a6a5dcbd786af68572d2c97b76262cd7f8/scripts/ci/lib.sh#L622
https://github.com/stackrox/scanner/blob/372710a6a5dcbd786af68572d2c97b76262cd7f8/scripts/ci/lib.sh#L696-L706
For these changes, I copied the `stackrox/stackrox` pattern for handling tagged builds in our GitHub Action workflow, which was added in this PR: https://github.com/stackrox/stackrox/pull/4239
Note: This needs to be cherry-picked into the `release-2.34` branch.
=> fix(ci): handle release builds in GHA CI workflow

.github/actions/handle-tagged-build/action.yaml, .github/workflows/ci.yaml, scripts/ci/lib.sh
Backporting #1561 to release branch to fix the 'tagging' on release builds currently affecting 4.5.0 (scanner 2.34.0)
=> fix(ci): backport #1561

.github/workflows/ci.yaml
The `push-manifests` job needs this as well, example using wrong tag: https://github.com/stackrox/scanner/actions/runs/9844546307/job/27180906936
=> fix(ci): one more place needs release build tag

scripts/ci/jobs/diff-dumps.sh
When RELEASE_VERSIONS.txt is updated to a new unreleased minor version, the `diff-dumps` job fails to upload the latest offline vulnerability data. That is because (as mentioned, the latest minor version does not exist, so we we attempt to pull its related data, there is nothing there.
This PR now will check if the latest version is unreleased. If that's the case, then it falls back to the latest released version, so offline vuln updates may continue.
We determine if there is a release by checking for the existence of the tag in the stackrox/stackrox repo. If it returns a 200, it exists. If it returns a 404, then it doesn't exist. Any other status code means there is some other kind of error, so we should fail
=> fix(ci): fallback to previous release when attempting unreleased version

.github/workflows/ci.yaml, scripts/ci/jobs/upload-dumps-for-downstream.sh
The `upload-dumps-for-downstream` job did not upload bundles with the appropriate tag - breaking downstream builds.
=> fix: add tag resolution for jobs missing it

go.mod, go.sum
This PR sets the correct `stackrox` dependency from commit with merged protobuf V2.
Executed commands:
```
go mod edit -replace github.com/stackrox/rox=github.com/stackrox/stackrox@cdfb007fd7e9dc81715f6324a38994541096f0ba
go mod tidy
```
=> ROX-22019: Set correct stackrox dependency with protobuf V2

.tekton/scanner-build.yaml, .tekton/scanner-db-build.yaml, .tekton/scanner-db-slim-build.yaml, .tekton/scanner-slim-build.yaml
This should enable Konflux CI on renovate PRs that update task bundles like this one <https://github.com/stackrox/scanner/pull/1575>. Notice its branch name does not mention `konflux` or `rhtap`.
Context: https://redhat-internal.slack.com/archives/C05TS9N0S7L/p1721753985769919
Testing: none, I hope it should just work.
=> build: Add "appstudio" to the PR branch name filter for Konflux CI

.tekton/scanner-build.yaml, .tekton/scanner-db-build.yaml, .tekton/scanner-db-slim-build.yaml, .tekton/scanner-slim-build.yaml
This should enable Konflux builds from release branches for the case when [SCANNER_VERSION](https://github.com/stackrox/stackrox/blob/master/SCANNER_VERSION) points to a tag/commit that was on a release branch, not on `master`.
See also: https://redhat-internal.slack.com/archives/C079XCJEZK6/p1721729454430659?thread_ts=1721678052.993799&cid=C079XCJEZK6
Prerequisite for <https://issues.redhat.com/browse/ROX-24468>.
Available CEL functions are here <https://github.com/google/cel-spec/blob/master/doc/langdef.md#list-of-standard-definitions>.
=> chore: Add `^release-` branches for on-push Konflux builds

.tekton/scanner-build.yaml, .tekton/scanner-db-build.yaml, .tekton/scanner-db-slim-build.yaml, .tekton/scanner-slim-build.yaml
Once PR is created with some branch name, it may be handy to enable Konflux builds on demand.
Inspiration from <https://pipelinesascode.com/docs/guide/authoringprs/#using-the-body-and-headers-in-a-pipelines-as-code-parameter> and <https://github.com/google/cel-spec/blob/master/doc/langdef.md#list-of-standard-definitions>.
=> build: Add Konflux pipeline activation through a label

.tekton/scanner-component-pipeline.yaml, image/scanner/rhel/Dockerfile, image/scanner/rhel/konflux.Dockerfile
Context is in the ticket.
Figured digests similarly to https://github.com/stackrox/collector/pull/1780
`chown /etc/pki` -> `chown /etc/pki/ca-trust` change was tested in https://github.com/stackrox/stackrox/pull/12337
=> ROX-25620: Switch to new Konflux task repos

go.mod, go.sum
Updates `github.com/docker/docker` to address [CVE-2024-41110](https://github.com/advisories/GHSA-v23v-6jw2-98fq) targeting Scanner `2.33.6` and Stackrox `4.4.5`
Expecting scanner version `2.33.6` to contain this change and be used in this backport: https://github.com/stackrox/stackrox/pull/12422
=> chore: Update docker dep to fix CVE-2024-41110

e2etests/testcase_test.go
Backports unit test fix from  #1567 and #1555
=> fix(e2e): update fixedBy versions (#1567)

.openshift-ci/pre_tests.py
Previous releases done completely via OpenShift CI take... forever. Increase the image poll time so tests can more reliably pass. This will be backported into `release-2.34` and `release-2.33` once merged.
=> fix: increase image poll timeout

.tekton/scanner-component-pipeline.yaml
Context: https://redhat-internal.slack.com/archives/C05TS9N0S7L/p1723738910783329
=> ROX-25623: reduce deprecated-image-check by feeding manifest

.tekton/scanner-component-pipeline.yaml
Recreates https://github.com/stackrox/scanner/pull/1613 without formatting changes.
https://issues.redhat.com/browse/KONFLUX-3663 related.
=> build: Upload SAST results

pkg/ioutils/lazy_reader_disk.go
to aid https://github.com/stackrox/stackrox/pull/12541
=> chore: swap mathutil with builtin

.tekton/scanner-component-pipeline.yaml, image/db/rhel/konflux.Dockerfile, image/scanner/rhel/konflux.Dockerfile
Validated that new check passes (except for the known issue of missing labels on multi-arch images due to KFLUXBUGS-1495).
=> ROX-25723: add ecosystem preflight check

image/scanner/rhel/konflux.Dockerfile
https://github.com/stackrox/scanner/pull/1634 bumped the Go version to 1.22, but I forgot to do it for Konflux, too
=> chore: go 1.22 konflux

e2etests/components_test.go, go.mod
This repository is deprecated, so this PR replaces its last remaining use with `google.golang.org/protobuf`.
=> chore: remove github.com/golang/protobuf direct dep

image/db/rhel/konflux.Dockerfile, image/scanner/rhel/konflux.Dockerfile
=> ROX-25565: Fail Konflux builds if required ARGs aren't provided

e2etests/testcase_test.go
Update e2e tests to account for [RHSA-2024:6783](https://access.redhat.com/errata/RHSA-2024:6783.html) which bumps the "fixed by" to `1:3.0.7-28.el9_4` for `openssl` and `openssl-libs`.
=> fix(e2e): Bump fixed by due to RHSA-2024:6783

cmd/updater/generatedump/cmd.go, e2etests/testcase_test.go, ext/vulnsrc/manual/manual.go, tools/allowed-large-files
Add entries for the recent CUPs vulnerabilities. The scores are from what NVD has now, which is from GitHub, except for Amazon which just uses Red Hat's scores. The main sources of this data are from the vendors, themselves, as well as NVD (kind of)
=> chore: track cups vulns

scripts/ci/jobs/diff-dumps.sh
Update the offline bundle workflow to use versioned offline definitions (create based on https://github.com/stackrox/stackrox/pull/12516/files) instead of release-based defintions. Also, from 4.6.x onward, versioned offline bundles are published by Z-stream.
See tests performed at https://github.com/stackrox/stackrox/pull/12895
=> ROX-25690: Use versioned offline defs in offline bundles

.tekton/scanner-build.yaml, .tekton/scanner-db-build.yaml, .tekton/scanner-db-slim-build.yaml, .tekton/scanner-slim-build.yaml
Let the Konflux team manage these resources as they seem to be on track of doing that
https://github.com/konflux-ci/build-definitions/pull/1247
=> build: Drop clamav-scan resource requests

.tekton/scanner-component-pipeline.yaml
Add new mandatory task to Konflux pipelines. The check is successful, e.g. https://console.redhat.com/application-pipeline/workspaces/rh-acs/applications/acs/pipelineruns/scanner-db-build-52j6z/logs?task=rpms-signature-scan. 
The [GH s390x failure](https://github.com/stackrox/scanner/actions/runs/11342081719/job/31544063009?pr=1671) is reported on [Slack](https://redhat-internal.slack.com/archives/C3W3U0RGW/p1728983880858899?thread_ts=1728469303.271559&cid=C3W3U0RGW).
=> ROX-26528: add rpms-signature-scan task to Konflux pipelines

.tekton/scanner-component-pipeline.yaml
After looking at <https://github.com/konflux-ci/release-service-catalog/blob/development/tasks/push-snapshot/push-snapshot.yaml>, I come to conclusion that the source container (the one with tag `sha256-<digest>.src`) is expected to have the digest of the index image, not some arch-specific image under it (in our case - amd64 one).
Likely, when we onboarded to multiarch, the use of amd64 was the only possible thing.
Now passing the index image as the argument for the source build seems to work without failures.
In fact all our containers except for `main` and scanner-v2's were set up properly.
I leave it as a bonus question why did not EC call out the source container related to an unexpected image.
=> ROX-24468: Link source container to the index image

.tekton/scanner-build.yaml, .tekton/scanner-slim-build.yaml
See https://github.com/stackrox/stackrox/pull/13101 for details.
Interestingly, scanner-db-s were already on `source_url`.
=> build: Switch `git-url` from `repo_url` to `source_url`

.tekton/determine-image-tag-task.yaml
Same as https://github.com/stackrox/collector/pull/1920. I hope it just works for Scanner.
=> ROX-26026: Make `determine-image-tag` recognize git tags

.tekton/scanner-build.yaml, .tekton/scanner-db-build.yaml, .tekton/scanner-db-slim-build.yaml, .tekton/scanner-slim-build.yaml
There are a couple of changes to the PipelineRun files:
* Update application and component names to match the ACS 4.6 release versions
* Update the CEL expression to only run ACS 4.6 pipelines on Scanner 2.35 PRs and pushes. All PRs to the release-2.35 branch will trigger Konflux builds.
=> ROX-26784: Configure tekton pipelines for release branch

.tekton/scanner-build.yaml, .tekton/scanner-db-build.yaml, .tekton/scanner-db-slim-build.yaml, .tekton/scanner-slim-build.yaml
This is primarily intended to stop triggering builds in Konflux for "master" components when there are PRs or pushes on release branches.
This retains the branch naming and label conventions to reduce load on Konflux.
=> ROX-26784: Don't trigger Konflux builds against release branches

image/db/rhel/konflux.Dockerfile, image/scanner/rhel/konflux.Dockerfile
Context: https://issues.redhat.com/browse/ROX-27485 and https://github.com/stackrox/stackrox/pull/13577
=> ROX-27485: Add comment not to delete source-location LABEL from Konflux Dockerfiles

.tekton/scanner-component-pipeline.yaml
See https://github.com/stackrox/stackrox/pull/13745
=> chore: Kill `Java` mentions from Konflux pipelines

Makefile, image/scanner/rhel/konflux.Dockerfile
Enables the strictfipsruntime build flag for the Konflux build.
For more info about the strictfipsruntime flag, see [this doc](https://docs.google.com/document/d/1CTpSwITQfOgoOTlPITZNJZy0ltYz60hxkmWsLemCqw0/edit?tab=t.0) (there might be a better resource but this is the one David and I found), and for our general research regarding the linked ticket, see [this doc](https://docs.google.com/document/d/1KcjlevcMF4DLi-KROru7tuUUIb4wSk5e6bnXpU8HZxA/edit?tab=t.0).
Related stackrox PR: https://github.com/stackrox/stackrox/pull/12909
Verified the build works via Konflux CI and verified the `check-payload` results of the following images:
=> ROX-24283: enable strictfipsruntime in the Konflux build

Makefile, api/v1/models.go, api/v1/models_rhelv2.go, api/v1/models_rhelv2_test.go, database/database.go, database/mock.go, database/models.go, database/pgsql/migrations/00021_rhel_layer_lineage.go, database/pgsql/queries.go, database/pgsql/rhelv2_layer.go, database/pgsql/rhelv2_layer_test.go, e2etests/testcase_test.go, worker.go
Fixes an edge case that could cause discrepancies in scan versions, packages, etc. when images have a common layer but with different parent layers.
Unit and e2e tests added.  Test image details at https://github.com/stackrox/stackrox/pull/13558
Also manually tested. The test images below have the same top/bottom layers but different middle layers, also they have tags that represent the version of the openjdk packages within the image for comparison.
**Before fix:**
Wrong version returned for 2nd scan:
```sh
$ rctl image scan -f --image=quay.io/dcaravel/temp:jdk-17.0.11.0.9-2.el8.x86_64 2>/dev/null | jq -r '.scan.components[] | select (.name == "java-17-openjdk-headless") | .name,.version'
java-17-openjdk-headless
1:17.0.11.0.9-2.el8.x86_64
```
```sh
$ rctl image scan -f …
```
=> ROX-26604: Add layer lineage to RHEL v2 data model

database/pgsql/rhelv2_layer.go, database/pgsql/rhelv2_layer_test.go, pkg/env/list.go
Builds on:
- https://github.com/stackrox/scanner/pull/1720
Adds env var `ROX_RHEL_LINEAGE` that when set to `false` disables the use of lineage when storing/retrieving image layers. Note: that the database migration still runs that adds the `lineage` and `parent_lineage` columns to `rhelv2_layer` (added in the previous PR) - however the empty string is inserted into both fields as images are analyzed.
Compared the results between two 4.6.1 ACS clusters with only the scanner image changed. A new scanner image was created based on 4.6.1 with only the scanner binary changed built from this PR. This was necessary because each PR includes a new genesis dump and even with the most recent vuln diffs applied scan results would differ.
To build the image:
```
FROM …
```
=> ROX-27618: Add env var to disable RHEL lineage usage

.github/workflows/ci.yaml
Add some leaf jobs in the dependency tree that were missing in the notification job dependencies, so that if these path fail, we see notifications.
=> fix: Add additional deps to the notification job

pkg/cpeutils/utils.go, pkg/cpeutils/utils_test.go
To assist with vuln matching for CPEs that do not have a `Y` version
=> Bump max known OCP version

.github/workflows/ci.yaml, .syft.yaml, scripts/ci/jobs/check-konflux-setup.sh
Adapted from https://github.com/stackrox/stackrox/pull/14065.
Ensured style check would fail in CI when `exclude` is empty: https://github.com/stackrox/scanner/actions/runs/13587104793/job/37984431483?pr=1819
When comparing actual sboms, I found no meaningful difference
```bash
$ cosign download sbom quay.io/rhacs-eng/scanner:2.36.x-8-g25fbd5cb83-fast-amd64 > pre-sbom.json
$ cosign download sbom quay.io/rhacs-eng/scanner:2.36.x-11-g14d6649088-fast-amd64 > post-sbom.json
$ wc -l *.json
58744 post-sbom.json
58744 pre-sbom.json
```
Also, unlike StackRox (see https://github.com/stackrox/stackrox/pull/14065), there were no redundant entries for `openssl` and no `fc35` mentions in SBOM before the change. I suppose there's something odd with `./pkg/rhelv2/rpm/testdata/rpmdb.sqlite` but I don't …
=> ROX-27905: Exclude example rpmdb from SBOMs

e2etests/utils.go
We observed the following error in a recent e2e CI run:
```
rpc error: code = ResourceExhausted desc = grpc: received message larger than max (4237137 vs. 4194304)`
```
Job link: https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/stackrox_scanner/1837/pull-ci-stackrox-scanner-release-2.36-e2e-tests/1902054308703113216
These changes increase the default max grpc receive message size.
=> fix: increase max grpc message size

.github/renovate.json5, image/db/rhel/konflux.Dockerfile, image/scanner/rhel/konflux.Dockerfile
See descriptions of individual commits.
1. Relying on CI signal.
2. Ran renovate validator cli.
3. I don't know how renovate config will actually work w.r.t. image digests and our custom tasks. I suggest merging this PR and monitoring things after.
=> ROX-20312: Pin base image digests and extend Renovate config

.github/renovate.json5
According to <https://konflux-ci.dev/docs/mintmaker/default-config/#rpm-updates>, there's nothing else we should touch.
I'll create a follow-up PR where I'd downgrade some package to let MintMaker create its update.
=> ROX-29108: Enable `rpm` lockfile renovation

ext/vulnsrc/rhel/rhel.go
Increases the timeout for the HTTP client that requests Red Hat OVAL feeds. We previously did this for the v2 feed in this PR: https://github.com/stackrox/scanner/pull/1820. However, our "v1" OVAL updater also uses the v2 feed URLs: 
https://github.com/stackrox/scanner/blob/5d2c067ca37b31db830daf54c1a66f4a679db459/ext/vulnsrc/rhel/rhel.go#L44
https://github.com/stackrox/scanner/blob/5d2c067ca37b31db830daf54c1a66f4a679db459/ext/vulnsrc/rhel/rhel.go#L54-L58
Moreover, these changes will keep the timeout consistent between reading from the "v1" and v2 Red Hat OVAL feeds.
Example of the error these changes should fix: https://github.com/stackrox/scanner/actions/runs/14848990112/job/41689019123
=> fix(ci): increase timeout processing RH OVAL data

.github/CODEOWNERS, .github/dependabot.yml
GitHub says the reviewers field will go away this month, and it should be replaced with CODEOWNERS
https://github.blog/changelog/2025-04-29-dependabot-reviewers-configuration-option-being-replaced-by-code-owners/
=> chore: remove reviewers and update CODEOWNERS

.tekton/scanner-build.yaml, .tekton/scanner-db-build.yaml, .tekton/scanner-db-slim-build.yaml, .tekton/scanner-slim-build.yaml
Announcement: https://groups.google.com/a/redhat.com/g/konflux-announce/c/NxOyzi8wGxo/m/QXRGc1QqCQAJ
=> ROX-29078: switch to per component SA

.tekton/scanner-component-pipeline.yaml
Validation
* [EC](https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-acs-tenant/applications/acs/pipelineruns/acs-enterprise-contract-qpxpd/security?component=scanner-db) doesn't show a missing task for `sast-shell-check`, `sast-unicode-check` and the [build pipeline](https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rh-acs-tenant/pipelinerun/scanner-db-on-push-cbrw8) passes.
=> ROX-28568: Add required tasks sast-shell-check and sast-unicode-check to Konflux pipelines

scripts/ci/jobs/diff-dumps.sh
If the http status code returned by the curl call is a status code we don't expect (i.e., the default case), we log that code. However, we don't assign the variable before executing the switch-case. Here's the error you might see:
```
./scripts/ci/jobs/diff-dumps.sh: line 165: status: unbound variable
```
Example: https://github.com/stackrox/scanner/actions/runs/15137116869/job/42551992695
=> fix(ci): assign the http status variable

.tekton/scanner-build.yaml, .tekton/scanner-db-build.yaml, .tekton/scanner-db-slim-build.yaml, .tekton/scanner-slim-build.yaml
Per title.
Only CI (Konflux and GHA should feel ok).
=> ROX-29690: Put -4-8 versions on Konflux resources

image/scanner/rhel/konflux.Dockerfile
1.23 got picked up during backporting in #1945. That's something I overlooked and spotted only in #1956.
=> ROX-27060: Downgrade Go from 1.23 to 1.22 for 4.6

e2etests/testcase_test.go
After #1999 was merged, yet another vuln came out to cause tests to fail...
=> e2e: update test to account for CVE-2025-52434

cmd/updater/diffdumps/rhelv2_diff.go, pkg/rhelv2/rhelv2.go, pkg/vulndump/write.go
Adds a copy of the `repository-to-cpe.json` file to root of the diff and offline bundles to address an issue where newer Central instances are not returning `repository-to-cpe.json` from the bundles `rhelv2/` dir.
Verified via the PR's CI artifacts that the copy of the file exists in both locations:
```
$ cd offline-dump/scanner-vuln-updates/scanner-defs 
$ find . -iname "repository-to-cpe*" -exec ls -l {} \;
-rw-r--r--@ 1 dcaravel  staff  1429794 Aug 20 19:49 ./repository-to-cpe.json
-rw-r--r--@ 1 dcaravel  staff  1429794 Aug 20 19:49 ./rhelv2/repository-to-cpe.json
$ cd diff-dumps-inspect
$ find . -iname "repository-to-cpe*" -exec ls -l {} \;
-rw-r--r--@ 1 dcaravel  staff  1429794 Aug 21 01:47 ./repository-to-cpe.json
-rw-r--r--@ 1 dcaravel  staff  1429794 Aug 21 01:47 …
```
=> ROX-30576: Copy repo 2 cpe to bundle root

.openshift-ci/pre_tests.py, e2etests/testcase_test.go, image/db/rhel/scripts/download.sh, scripts/ci/deploy.sh
Backports https://github.com/stackrox/scanner/pull/2092 to fix s390x builds and #2149 to fix CI tests
ALSO - bumps deploy wait time to 30m (up from 20m) - newer release versions were OK at 20m
Targeting Scanner 2.35 (StackrRox 4.6)
=> Backport s390x and CI fixes - 2.35/4.6

.tekton/scanner-component-pipeline.yaml
For easier reading.
They were killed by some MintMaker's migration but I haven't figured which one.
Release branches don't need this change, they are fine.
=> chore: Restore empty lines in `scanner-component-pipeline`

.github/renovate.json5, .tekton/scanner-component-pipeline.yaml
Cherry-picks of
1. https://github.com/stackrox/scanner/pull/2195
2. https://github.com/stackrox/scanner/pull/2201
Only CI.
=> ROX-30898, ROX-30899: Konflux backports / 4.7

.github/renovate.json5
Changes here:
1. Foremost: reduce frequency for Task renovation to do that once per week.
2. Remove schedule overrides following the recent announcement <https://groups.google.com/a/redhat.com/g/konflux-announce/c/atbFtt5ad7Y/m/wzl0u96OAAAJ>.
3. Bump concurrent PR limits following the StackRox example <https://github.com/stackrox/stackrox/pull/16877>.
4. Reformat the file.
Only ran the config validator. It complains about the unknown `rpm-lockfile`. Otherwise, it's ok.
In general and as always, I don't know how it will work. Let's apply and see.
=> ROX-30592: Adjust renovate config

.github/actions/job-preamble/action.yaml
We've been seeing `No space left on device` errors in our GitHub Actions, example: https://github.com/stackrox/scanner/actions/runs/18006964847/job/51231202997
These changes ported over the disk freeing logic from the stackrox/stackrox job-preamble action.
=> chore(ci): port job-preamble disk freeing steps

.github/renovate.json5
This partially undoes what I did in https://github.com/stackrox/scanner/pull/2200.
While describing the release process and revising [How to handle MintMaker updates during the release process](https://spaces.redhat.com/spaces/StackRox/pages/661160921/How+to+handle+MintMaker+updates+during+the+release+process), I realized that we ask release engineers to land MintMaker PRs but these may not be ready for Y-Stream with the current "on the weekend" schedule after the release engineer just created GitOps resources.
Therefore, I suggest to enable more frequent tasks renovation as a tradeoff to let release engineers not get stuck.
We'll have to deal with email and commit traffic some other way.
Only ran config validator.
=> ROX-30592: Enable tekton Tasks renovation every day
